Mirai: loader/src/headers/util.h File Reference
util.h File Reference
#include "server.h"
#include "includes.h"
Data Structures
struct elf_hdr
Macros
#define BUFFER_SIZE 4096
#define EI_NIDENT 16
#define EI_DATA 5
#define EE_NONE 0
#define EE_LITTLE 1
#define EE_BIG 2
#define ET_NOFILE 0
#define ET_REL 1
#define ET_EXEC 2
#define ET_DYN 3
#define ET_CORE 4
#define EM_NONE 0
#define EM_M32 1
#define EM_SPARC 2
#define EM_386 3
#define EM_68K 4
#define EM_88K 5
#define EM_486 6
#define EM_860 7
#define EM_MIPS 8 /* MIPS R3000 (officially, big-endian only) */
#define EM_MIPS_RS3_LE 10 /* MIPS R3000 little-endian */
#define EM_MIPS_RS4_BE 10 /* MIPS R4000 big-endian */
#define EM_PARISC 15 /* HPPA */
#define EM_SPARC32PLUS 18 /* Sun's "v8plus" */
#define EM_PPC 20 /* PowerPC */
#define EM_PPC64 21 /* PowerPC64 */
#define EM_SPU 23 /* Cell BE SPU */
#define EM_ARM 40 /* ARM 32 bit */
#define EM_SH 42 /* SuperH */
#define EM_SPARCV9 43 /* SPARC v9 64-bit */
#define EM_H8_300 46 /* Renesas H8/300 */
#define EM_IA_64 50 /* HP/Intel IA-64 */
#define EM_X86_64 62 /* AMD x86-64 */
#define EM_S390 22 /* IBM S/390 */
#define EM_CRIS 76 /* Axis Communications 32-bit embedded processor */
#define EM_M32R 88 /* Renesas M32R */
#define EM_MN10300 89 /* Panasonic/MEI MN10300, AM33 */
#define EM_OPENRISC 92 /* OpenRISC 32-bit embedded processor */
#define EM_BLACKFIN 106 /* ADI Blackfin Processor */
#define EM_ALTERA_NIOS2 113 /* Altera Nios II soft-core processor */
#define EM_TI_C6000 140 /* TI C6X DSPs */
#define EM_AARCH64 183 /* ARM 64 bit */
#define EM_TILEPRO 188 /* Tilera TILEPro */
#define EM_MICROBLAZE 189 /* Xilinx MicroBlaze */
#define EM_TILEGX 191 /* Tilera TILE-Gx */
#define EM_FRV 0x5441 /* Fujitsu FR-V */
#define EM_AVR32 0x18ad /* Atmel AVR32 */
Functions
struct elf_hdr __attribute__ ((packed))
int util_socket_and_bind (struct server *srv)
int util_memsearch (char *buf, int buf_len, char *mem, int mem_len)
BOOL util_sockprintf (int fd, const char *fmt,...)
char * util_trim (char *str)
Variables
uint8_t e_ident [EI_NIDENT]
uint16_t e_type
uint16_t e_machine
uint32_t e_version
Macro Definition Documentation
#define BUFFER_SIZE 4096
Definition at line 6 of file util.h.
Referenced by util_sockprintf().
#define EE_BIG 2
Definition at line 13 of file util.h.
Referenced by connection_consume_arch().
#define EE_LITTLE 1
Definition at line 12 of file util.h.
Referenced by connection_consume_arch().
#define EE_NONE 0
Definition at line 11 of file util.h.
Referenced by connection_consume_arch().
#define EI_DATA 5
Definition at line 9 of file util.h.
Referenced by connection_consume_arch().
#define EI_NIDENT 16
Definition at line 8 of file util.h.
#define EM_386 3
Definition at line 25 of file util.h.
Referenced by connection_consume_arch().
#define EM_486 6
Definition at line 28 of file util.h.
Referenced by connection_consume_arch().
#define EM_68K 4
Definition at line 26 of file util.h.
Referenced by connection_consume_arch().
#define EM_860 7
Definition at line 29 of file util.h.
Referenced by connection_consume_arch().
#define EM_88K 5
Definition at line 27 of file util.h.
Referenced by connection_consume_arch().
#define EM_AARCH64 183 /* ARM 64 bit */
Definition at line 56 of file util.h.
Referenced by connection_consume_arch().
#define EM_ALTERA_NIOS2 113 /* Altera Nios II soft-core processor */
Definition at line 54 of file util.h.
#define EM_ARM 40 /* ARM 32 bit */
Definition at line 42 of file util.h.
Referenced by connection_consume_arch().
#define EM_AVR32 0x18ad /* Atmel AVR32 */
Definition at line 61 of file util.h.
#define EM_BLACKFIN 106 /* ADI Blackfin Processor */
Definition at line 53 of file util.h.
#define EM_CRIS 76 /* Axis Communications 32-bit embedded processor */
Definition at line 49 of file util.h.
#define EM_FRV 0x5441 /* Fujitsu FR-V */
Definition at line 60 of file util.h.
#define EM_H8_300 46 /* Renesas H8/300 */
Definition at line 45 of file util.h.
#define EM_IA_64 50 /* HP/Intel IA-64 */
Definition at line 46 of file util.h.
#define EM_M32 1
Definition at line 23 of file util.h.
#define EM_M32R 88 /* Renesas M32R */
Definition at line 50 of file util.h.
#define EM_MICROBLAZE 189 /* Xilinx MicroBlaze */
Definition at line 58 of file util.h.
#define EM_MIPS 8 /* MIPS R3000 (officially, big-endian only) */
Definition at line 30 of file util.h.
Referenced by connection_consume_arch().
#define EM_MIPS_RS3_LE 10 /* MIPS R3000 little-endian */
Definition at line 34 of file util.h.
Referenced by connection_consume_arch().
#define EM_MIPS_RS4_BE 10 /* MIPS R4000 big-endian */
Definition at line 35 of file util.h.
#define EM_MN10300 89 /* Panasonic/MEI MN10300, AM33 */
Definition at line 51 of file util.h.
#define EM_NONE 0
Definition at line 22 of file util.h.
#define EM_OPENRISC 92 /* OpenRISC 32-bit embedded processor */
Definition at line 52 of file util.h.
#define EM_PARISC 15 /* HPPA */
Definition at line 37 of file util.h.
#define EM_PPC 20 /* PowerPC */
Definition at line 39 of file util.h.
Referenced by connection_consume_arch().
#define EM_PPC64 21 /* PowerPC64 */
Definition at line 40 of file util.h.
Referenced by connection_consume_arch().
#define EM_S390 22 /* IBM S/390 */
Definition at line 48 of file util.h.
#define EM_SH 42 /* SuperH */
Definition at line 43 of file util.h.
Referenced by connection_consume_arch().
#define EM_SPARC 2
Definition at line 24 of file util.h.
Referenced by connection_consume_arch().
#define EM_SPARC32PLUS 18 /* Sun's "v8plus" */
Definition at line 38 of file util.h.
Referenced by connection_consume_arch().
#define EM_SPARCV9 43 /* SPARC v9 64-bit */
Definition at line 44 of file util.h.
Referenced by connection_consume_arch().
#define EM_SPU 23 /* Cell BE SPU */
Definition at line 41 of file util.h.
#define EM_TI_C6000 140 /* TI C6X DSPs */
Definition at line 55 of file util.h.
#define EM_TILEGX 191 /* Tilera TILE-Gx */
Definition at line 59 of file util.h.
#define EM_TILEPRO 188 /* Tilera TILEPro */
Definition at line 57 of file util.h.
#define EM_X86_64 62 /* AMD x86-64 */
Definition at line 47 of file util.h.
Referenced by connection_consume_arch().
#define ET_CORE 4
Definition at line 19 of file util.h.
#define ET_DYN 3
Definition at line 18 of file util.h.
#define ET_EXEC 2
Definition at line 17 of file util.h.
#define ET_NOFILE 0
Definition at line 15 of file util.h.
#define ET_REL 1
Definition at line 16 of file util.h.
Function Documentation
struct elf_hdr __attribute__ ((packed))
int util_memsearch (char * buf, int buf_len, char * mem, int mem_len)
Definition at line 111 of file util.c.
Referenced by attack_app_http(), connection_consume_arch(), connection_consume_arm_subtype(), connection_consume_cleanup(), connection_consume_copy_op(), connection_consume_login_prompt(), connection_consume_mounts(), connection_consume_password_prompt(), connection_consume_psoutput(), connection_consume_upload_methods(), connection_consume_verify_login(), connection_consume_written_dirs(), connection_upload_echo(), connection_upload_tftp(), connection_upload_wget(), and connection_verify_payload().
 {
     int i, matched = 0;
     if (mem_len > buf_len)
         return -1;
     for (i = 0; i < buf_len; i++)
     {
         if (buf[i] == mem[matched])
         {
             if (++matched == mem_len)
                 return i + 1;
         }
         else
             matched = 0;
     }
     return -1;
 }
int util_socket_and_bind (struct server * srv)
Definition at line 64 of file util.c.
References server::bind_addrs, server::bind_addrs_len, close, FALSE, socket, and TRUE.
Referenced by server_telnet_probe().
 {
     struct sockaddr_in bind_addr;
     int i, fd, start_addr;
     BOOL bound = FALSE;
     if ((fd = socket(AF_INET, SOCK_STREAM, 0)) == -1)
         return -1;
     bind_addr.sin_family = AF_INET;
     bind_addr.sin_port = 0;
     // Try to bind on the first available address
     start_addr = rand() % srv->bind_addrs_len;
     for (i = 0; i < srv->bind_addrs_len; i++)
     {
         bind_addr.sin_addr.s_addr = srv->bind_addrs[start_addr];
         if (bind(fd, (struct sockaddr *)&bind_addr, sizeof (struct sockaddr_in)) == -1)
         {
             if (++start_addr == srv->bind_addrs_len)
                 start_addr = 0;
         }
         else
         {
             bound = TRUE;
             break;
         }
     }
     if (!bound)
     {
         close(fd);
 #ifdef DEBUG
         printf("Failed to bind on any address\n");
 #endif
         return -1;
     }
     // Set the socket in nonblocking mode
     if (fcntl(fd, F_SETFL, fcntl(fd, F_GETFL, 0) | O_NONBLOCK) == -1)
     {
 #ifdef DEBUG
         printf("Failed to set socket in nonblocking mode. This will have SERIOUS performance implications\n");
 #endif
     }
     return fd;
 }
BOOL util_sockprintf (int fd, const char * fmt, ...)
Definition at line 132 of file util.c.
References BUFFER_SIZE, FALSE, hexDump(), and TRUE.
Referenced by connection_consume_mounts(), connection_consume_psoutput(), connection_consume_written_dirs(), connection_upload_echo(), handle_event(), and timeout_thread().
 {
     char buffer[BUFFER_SIZE + 2];
     va_list args;
     int len;
     va_start(args, fmt);
     len = vsnprintf(buffer, BUFFER_SIZE, fmt, args);
     va_end(args);
     if (len > 0)
     {
         if (len > BUFFER_SIZE)
             len = BUFFER_SIZE;
 #ifdef DEBUG
         hexDump("TELOUT", buffer, len);
 #endif
         if (send(fd, buffer, len, MSG_NOSIGNAL) != len)
             return FALSE;
     }
     return TRUE;
 }
char* util_trim (char * str)
Definition at line 157 of file util.c.
Referenced by main().
 {
     char *end;
     while(isspace(*str))
         str++;
     if(*str == 0)
         return str;
     end = str + strlen(str) - 1;
     while(end > str && isspace(*end))
         end--;
     *(end+1) = 0;
     return str;
 }
Variable Documentation
uint8_t e_ident[EI_NIDENT]
Definition at line 15 of file util.h.
uint16_t e_machine
Definition at line 16 of file util.h.
uint16_t e_type
Definition at line 16 of file util.h.
uint32_t e_version
Definition at line 17 of file util.h.