Mirai: mirai/bot/scanner.h File Reference
scanner.h File Reference
#include <stdint.h>
#include "includes.h"
Data Structures
struct scanner_auth
struct scanner_connection
Macros
#define SCANNER_MAX_CONNS 128
#define SCANNER_RAW_PPS 160
#define SCANNER_RDBUF_SIZE 256
#define SCANNER_HACK_DRAIN 64
Functions
void scanner_init ()
void scanner_kill (void)
static void setup_connection (struct scanner_connection *)
static ipv4_t get_random_ip (void)
static int consume_iacs (struct scanner_connection *)
static int consume_any_prompt (struct scanner_connection *)
static int consume_user_prompt (struct scanner_connection *)
static int consume_pass_prompt (struct scanner_connection *)
static int consume_resp_prompt (struct scanner_connection *)
static void add_auth_entry (char *, char *, uint16_t)
static struct scanner_auth * random_auth_entry (void)
static void report_working (ipv4_t, uint16_t, struct scanner_auth *)
static char * deobf (char *, int *)
static BOOL can_consume (struct scanner_connection *, uint8_t *, int)
Macro Definition Documentation
#define SCANNER_HACK_DRAIN 64
Definition at line 16 of file scanner.h.
#define SCANNER_MAX_CONNS 128
Definition at line 11 of file scanner.h.
#define SCANNER_RAW_PPS 160
Definition at line 12 of file scanner.h.
#define SCANNER_RDBUF_SIZE 256
Definition at line 15 of file scanner.h.
Function Documentation
static void add_auth_entry (char * , char * , uint16_t) static
static BOOL can_consume (struct scanner_connection * , uint8_t * , int) static
static int consume_any_prompt (struct scanner_connection *) static
static int consume_iacs (struct scanner_connection *) static
static int consume_pass_prompt (struct scanner_connection *) static
static int consume_resp_prompt (struct scanner_connection *) static
static int consume_user_prompt (struct scanner_connection *) static
static char* deobf (char * , int *) static
static ipv4_t get_random_ip (void) static
static struct scanner_auth* random_auth_entry (void) static
static void report_working (ipv4_t , uint16_t , struct scanner_auth *) static
void scanner_init ()
Referenced by attack_kill_all(), and main().
void scanner_kill (void)
Referenced by main().
static void setup_connection (struct scanner_connection *) static